metabrainz/bookbrainz-site

app.js, lib/auth.js, lib/passport-bookbrainz-ws.js, package.json, routes/editor.js, routes/entity/create/creator.js, routes/entity/create/publication.js, routes/entity/view/view.js, routes/index.js, routes/login.js, routes/message.js, routes/register.js, routes/relationship/edit.js, views/editor/editor.jade, views/editor/edits.jade, views/navbar.jade
This doesn't currently make use of the auth.isAuthenticated() function, which will be done on a route-by-route basis, but it does appear to work with all existing code, with exceptions noted in the message for the second commit.
=> Implement passport.js authentication

app.js, lib/auth.js, lib/passport-bookbrainz-ws.js, package.json, routes/editor.js, routes/entity/create/creator.js, routes/entity/create/publication.js, routes/entity/view/view.js, routes/index.js, routes/login.js, routes/message.js, routes/register.js, routes/relationship/edit.js, views/editor/editor.jade, views/editor/edits.jade, views/navbar.jade
This doesn't currently make use of the auth.isAuthenticated() function, which will be done on a route-by-route basis, but it does appear to work with all existing code, with exceptions noted in the message for the second commit.
=>  Implement passport.js authentication

README.md, config/development.json.example
i would have been quicker to start experimenting with bookbrainz-site if those patches were applied, i hope they are found useful.
=> make running an own bookbrainz-site easier

src/server/data/properties/annotation.js, static/stylesheets/style.css, templates/entity/view/creator.jade, templates/entity/view/edition.jade, templates/entity/view/publication.jade, templates/entity/view/publisher.jade, templates/entity/view/work.jade, templates/index.jade
Added annotations to entity views and added entity icons.
=> July 2015 entity views

.eslintrc, src/client/components/forms/edition.jsx, src/client/components/forms/parts/editionData.jsx, src/server/data/entities/edition.js, src/server/routes/entity/edition.js, templates/entity/view/edition.jade
This set of changes adds the ability to view and edit the physical properties of editions stored in the database.
=> Physical properties

.jscsrc, src/server/data/properties/revision.js, src/server/routes.js, src/server/routes/revision.js, templates/revision.jade
This set of changes provides an interface for viewing the details of both entity and relationship revisions. In future, this could be extended to allow commenting on and "starring" of revisions.
=> Revision detail

src/client/components/forms/parts/aliases.jsx
I first added a buttonAfter to the Alias sortName input. Afterwards, I created a guess() function that reads the name of the alias and sets the sortName input value to a generates a "guess" based on naming standards.
Although this guess method will not correctly apply to some cases, many entries will benefit from the usage of a quick generator.
http://tickets.musicbrainz.org/browse/BB-101
=> BB-101: Added guess button and logic to alias sortName

src/client/stylesheets/style.less
Screenshots available at [ticket](http://tickets.musicbrainz.org/browse/BB-154).
=> BB-154: Aligned search input field and search button.

templates/entity/view/publication.jade, templates/entity/view/publisher.jade
http://tickets.musicbrainz.org/browse/BB-149
=> BB-149: Display disambig. in Edts. table for publication and publisher

README.md
I have just set up the development environment and have found a two sections slightly confusing that required checking some outside resources, included are the commands I used to get it working
=> Minor changes to instructions from readme

package.json, src/server/helpers/achievement.js, src/server/helpers/utils.js, src/server/routes/entity/entity.js, test/bookbrainz-data.js, test/testAchievement.js
Produce start of achievement module for BookBrainz
Implements a "Revisionist" achievement awarded to anyone with a revision attached to their account
Effects the editing of an entity, when an entity is edited, the processEdit function is called which will call all process<Achievements> later into the modules development
=> Gamification dummy functions

data/testData.js, src/server/helpers/achievement.js, test/testAchievement.js, test/testCreatorCreator.js, test/testFunRunner.js, test/testLimitedEdition.js, test/testMarathoner.js, test/testPublisher.js, test/testRevisionist.js, test/testSprinter.js
More Achievements are needed in the gamification system to make it more engaging
Supply two new achievements, Marathoner and Fun Runner along with unit tests for them
1. Achievement module
2. Unit tests for achievement module
=> New achievements

package.json, src/server/helpers/achievement.js
Add HTML documentation to the BookBrainz project
Adds JSdoc to the project and document the achievement module
Package.json
Achievement Module
=> Achievement jsdoc

src/client/components/pages/revision.jsx, src/server/routes/revision.js
Titles are only integrated into the profile page, it would be good to have them in other areas of the site
Integrates titles into revision page such that you can hover over them and see the users title
Revision page
Revision route
=> Title integration

data/testData.js, package.json, src/server/helpers/achievement.js, src/server/helpers/error.js, src/server/routes/entity/entity.js, test/testAchievement.js, test/testExplorer.js
No achievement to encourage looking around the entities on the site
Explorer achievement is obtained by viewing many entities on the site
Entity route
Entity page
Unit tests
Achievement module
=> Explorer achievement

.babelrc, .eslintrc, package.json, src/client/components/footer.js, src/client/components/layout.js, src/client/components/pages/index.js, src/server/app.js, src/server/routes/index.js, templates/target.jade
**Note:** This PR is a work in progress, there are still many quirks that need to be fixed (i.e. eslint errors). I just wanted to get this out as soon as possible so that more people could get involved.
The codebase is currently split between Pug templates and React components. It has also come to my attention that React in this project isn't being used to its fullest capabilities. Although there has been progress in moving over to React, markup for React is still being rendered on different pug templates and pug template inheritance is still being used widely.
This PR aims to be a starting point for a proper conversion to React, starting off with a component replacement for the base layout.jade file and an Index component that is rendered as its child.
This is what the JSX markup looks …
=> Converting Pug/Jade templates to React - GCI

src/client/components/input/select2.js, src/client/components/pages/search.js, src/server/routes/search.js
Lack of documentation makes maintaining the project harder and puts a higher bar of entry for new developers.
Added JSDoc style annotations to a few server and client files.
Annotations should not alter the behaviour of any existing code.
=> JSDoc additions - GCI

src/client/components/forms/relationship.js
Thanks for the feedback on the previous documentation! Here are the edited JSDoc comments. I wasn't quite sure how to talk about how a function works in the bigger scale of the program, so I may need to go back and fix that if it's not clear enough. Let me know if there's anything which needs to be changed.
Thanks!
=> Add edited JSDoc comments to relationship.js

.babelrc, .eslintrc, package.json, src/server/helpers/auth.js, src/server/routes/index.js
Promise chains can become awkward and introduce difficulties in both structuring and following code.
Make use of es2017 async/await syntax to hide the grittier parts of Promise syntax.
Main page, user auth, babel compilation.
=> Introduce es2017 async/await

src/client/components/forms/creator.js
Documentation is a very important part in Open source project which is not present in the document and it makes it difficult for new developers to collaborate as well as existing developers to remember what they wrote and why they wrote it. 
Adding JSdocs comments to methods and their parameters and return values make the code understandable.
JSdocs comments will not affect any part of the codebase
=> Add JSdocs comments for Creator form methods

.eslintrc, src/client/components/pages/about.js, src/client/components/pages/contribute.js, src/client/components/pages/develop.js, src/client/components/pages/entity-revisions.js
Documentation is a very important part in Open source project which is not present in the document and it makes it difficult for new developers to collaborate as well as existing developers to remember what they wrote and why they wrote it.
Adding JSdocs comments to methods and their parameters and return values make the code understandable.
JSdocs comments will not affect any part of the codebase
=> Add JSdocs comments

src/client/components/forms/profile.js, src/client/components/pages/parts/editor-profile.js, src/client/controllers/editor/edit.js, src/server/routes/editor.js
Current profile editor form does not expose all user-related field, i.e. gender, birth date and display name.
Adds new form inputs for the above three fields and updates server handler for profile edits. Also moved most of the rendering to React.
Code in the editor route used for rendering profile form and receiving profile edits. Updated the profile react component. Updated the client side controller to use the Layout component.
GOTCHAS:
- Title field in the original profile editor form did not include a default title value, so this was left out until further clarification.
- Date field is always decremented by 1 day server side. This behaviour seems like it existed in master before this change though.
=> Profile editor extension - GCI

src/client/components/pages/privacy.js, src/client/components/pages/registration-auth.js
JSDoc comments would help the user to understand the function clearly
=> Added JSDoc comments in registration-auth.js and privacy.js

src/client/components/pages/error.js, src/server/app.js, src/server/helpers/error.js, src/server/routes/editor.js, src/server/routes/search.js
Current error component is being rendered solely with Pug, looks horrible, and does not display any useful information.
Modifies server code to send down more detailed responses with information taken from the req object, creates an error page react component, adds a bit more styling to the original page.
Makes non-breaking updates to all Error constructors to include the req express object and detailed message field. Modifies 404 handler to render down page with React. 
PR isn't complete. A detailed message has only been created for the 404 status code. Would like to get some feedback on this approach before continuing further.
=> New error component - GCI

src/client/components/input/drag-and-drop-image.js, src/client/components/input/partial-date.js
Documentation is a very important part in Open source project which is not present in the document and it makes it difficult for new developers to collaborate as well as existing developers to remember what they wrote and why they wrote it.
Adding JSdocs comments to methods and their parameters and return values make the code understandable.
JSdocs comments will not affect any part of the codebase
=> Add JSdoc comments to Input Component files

src/client/components/forms/publisher.js
Adding documentation to files in the src/client/components/forms/ directory
Adds documentation to the publisher.js file.
No behavior has been changed.
=> Add documentation to PublisherEditor component

.eslintrc, data/test-data.js, src/client/components/footer.js, src/client/components/forms/deletion.js, src/client/components/forms/profile.js, src/client/components/input/entity-search.js, src/client/containers/entity.js, src/client/containers/layout.js, src/client/entity-editor/common/date-field.js, src/client/entity-editor/common/entity-search-field.js, src/client/entity-editor/common/name-field.js, src/client/entity-editor/common/sort-name-field.js, src/client/entity-editor/common/validation-label.js, src/client/entity-editor/creator-section/creator-section.js, src/client/entity-editor/edition-section/edition-section.js, src/client/entity-editor/identifier-editor/identifier-row.js, src/client/entity-editor/publication-section/publication-section.js, src/client/entity-editor/publisher-section/publisher-section.js, src/client/entity-editor/work-section/work-section.js, src/client/helpers/entity.js, src/server/app.js, src/server/helpers/config.js, src/server/helpers/middleware.js, src/server/helpers/search.js, src/server/helpers/utils.js, src/server/routes/entity/entity.js, src/server/routes/index.js, test/custom_commands/customSauceEnd.js
Lots of linting warnings and errors.
Partial sweep fixing lint.
The only functional change is in displaying recent edits.
=> Linting cleanup

templates/target.jade
Webpage did not adjust size responsively for mobile. 
Added meta tag to scale mobile page width to the device width.
=> fix: mobile page width now scales with device width

src/server/helpers/search.js
The current search configuration produces unintuitive results.
Use the ngram tokenizer instead of filter, which improves the relevance of items with adjacent ngram matches. As a bonus, boost exact word matches.
Search indexing and results.
=> Improve search precision

src/server/routes/entity/publication.js
Add Publisher => Add Publication
=> Fixed title of publication page

test/common.js, test/test-creator-creator.js, test/test-explorer.js, test/test-fun-runner.js, test/test-hot-off-the-press.js, test/test-limited-edition.js, test/test-marathoner.js, test/test-publisher-creator.js, test/test-publisher.js, test/test-revisionist.js, test/test-sprinter.js, test/test-time-traveller.js, test/test-worker-bee.js
Reduce the amount of code that needs to be maintained for testing.
Factor out common assertion patterns
This affects most `.js` files directly in the `test/` directory and doesn't change any behaviour.
=> refactor(tests): Rewrite achievement tests

src/client/components/pages/about.js, src/client/components/pages/contribute.js, src/client/containers/layout.js, src/client/helpers/props.js, src/server/app.js, src/server/helpers/props.js
There's no indication on the site when redis isn't up.
Add scaffolding to show alerts on the site, use this to display a message when we can't find a session.
Page display.
=> Show no-session alert

.eslintrc.js, src/server/helpers/search.js, test/.eslintrc.js
Reindexing can flood elasticsearch's queue, causing the reindexing operations to halt.
Use bulk operations to batch up indexing operations.
Reindexing.
=> Use bulk search operations during reindexing

config/config.json.example, src/server/helpers/search.js
Bulk indexing was failing to index many entities.
Bump the bulk operation size to try to reduce the chances of silent indexing failure. Only index the master revision of entities for which the master revision includes entity data.
Search indexing.
=> Improve search indexing

src/client/components/pages/index.js
It had required the redirect to Metabrainz ticket.
Update with current URL of Metabrainz JIRA.
src/client/components/pages/index.js b/src/client/components/pages/index.js
=> Change MusicBrainz JIRA to MetaBrainz JIRA on homepage.

src/server/routes/entity/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js
Fixes BB-228(Sort Editions)
Added SortByDate function in order to sort the editions according to release date.
=> Fix(Unsorted Editions):Sorted Editions according to date.

scripts/build-client-js.sh
Added uglifyjs support for minification
Added uglifyjs to minify output
pipe output to uglifyjs
build script files
=> browserif-optimizations-kartikohri1712

README.md
When I'm building BookBrainz from scratch, I'm having a difficulty with PostgreSQL Password
In order to set things right and not to confuse others who want to build BookBrainz, I added information about PostgreSQL password
Documentation
=> doc(readme): Add information about PostgreSQL password

README.md
Issue #BB-317
relplaced "MANUAL_INSTALL.md" link to "DEPENDENCIES_MANUAL_INSTALL.md"
README.md
=> fix #BB-317

src/client/entity-editor/common/entity.js
Use brackets and small size for consistency as a search result.
=> fix #BB-318 and make same as shown in search result

README.md
Setup bookbrainz locally using docker toolbox
Added a note in README.md in "Running dependencies using Docker" section
Nothing
=> docs: bookbrainz setup locally using docker toolbox

src/client/stylesheets/style.less
=> fix footer position for all size of devices

src/client/components/forms/profile.js, src/client/components/forms/registration-details.js, src/client/components/pages/parts/editor-profile.js, src/client/helpers/utils.js, src/server/routes/editor.js, src/server/routes/register.js
***Client-side***
`src/client/components/forms/profile.js`  
`src/client/components/forms/registration-details.js`  
`src/client/components/pages/parts/editor-profile.js`  
`src/client/helpers/utils.js`
***Server-side***
`src/server/routes/editor.js`  
`src/server/routes/register.js`
=> remove date of birth of user or editor from whole website to fix #BB-319.

.eslintrc.js, src/client/components/pages/entities/identifiers-links.js, src/client/components/pages/entities/identifiers.js
Identifiers have not linked with any URL.
Identifiers are linked with related URL. 
Identifier section of the entity page.
=> feat(identifiers links): Add links to  most of all identifiers to fix #BB-273

src/client/components/forms/deletion.js
The deletion confirmation text was not dissuasive enough and didn't offer clear alternatives
Add an unavoidable warning and suggest non-destructive solutions
Added icons on the buttons as well, while I was there…
`src/client/components/forms/deletion.js`
=> refactor(deletion): Added instructions in deletion confirmation text

sql/migrations/2019-01-27/down.sql, sql/migrations/2019-01-27/up.sql, sql/schemas/bookbrainz.sql
Issue BB-320
- Removed birth_date from the schema definition
- Added migrations
Database
=> fix: BB-320

src/client/entity-editor/name-section/name-section.js
When creating a new Edition from a Work, the nameSection is copied over from the Work.
The deduplication search mechanism is not run in this case, and does not enforce a disambiguation even though another edition of the same name exists.
Turn NameSection functionnal component into class in order to use the `componentDidMount` lifecycle hook.
This is also a more elegant solution to the stopgap fix that was in place to fix an issue if a user types in the input before component is mounted (i.e. with slow loading JS)
`src/client/entity-editor/name-section/name-section.js`
=> fix(editor): Fix BB-332: Run name deduplication search on component mount

.gitignore, package-lock.json, package.json, src/client/stylesheets/style.less
Security alert from Github about  Bootstrap < 3.4.1
=> refactor(security-alert): Update to Bootstrap 3.4.1

src/client/components/input/entity-search.js, src/client/entity-editor/common/entity-search-field.js, src/server/routes/entity/edition.js, src/server/routes/entity/work.js
The edition was added when Publication was not compulsory in Edition form. 
Check that publicationBbid is available or not.
`src/server/routes/entity/edition.js`
=> fix(server): fix issue #BB-336 by checking publicationBbid is available or not

src/server/routes.js
Maintaining code consistency
Create a new function initEditorRoutes to fix the problem
./src/server/routes.js file
=> refactor(code): Created initEditorRoutes function to mantain code consistency

Dockerfile, config/config.json.ctmpl, config/config.json.example, docker/consul-template-webserver.conf, docker/prod/webserver.command, docker/test/webserver.service, package.json, src/server/app.js, src/server/helpers/appCleanup.js
Need to migrate test.BB as well.
Not much, make the database name a configurable value.
Right now I've made new.BB and test-new.BB both connect to the same elasticsearch and redis instance. Is this gonna be a problem, or will the indexes/rediskeys have different names / be independent?
See this in action at https://test-new.bookbrainz.org, I think we can make test.bookbrainz.org point to gateways now and shut down test.BB in the VM.
=> test.bookbrainz.org on hetzner

config/config.json.ctmpl, docker/beta/webserver.command, docker/beta/webserver.service
Prepare for:
1. a new beta.bookbrainz.org container
2. a separate elasticsearch instance for the test.bookbrainz container
=> Consul: Beta and test container configurations

README.md
=> feat(README): Add message for temporary use of stable branch

Dockerfile, docker/beta/rc.local, docker/consul-template-cron.conf, docker/consul-template.conf, docker/crontab, docker/prod/cron.service, docker/prod/rc.local, docker/test/rc.local, scripts/config.sh.ctmpl, scripts/create-dumps.sh, scripts/functions.sh, scripts/rsync-dump-files.sh
The cron and data dumps setup hadn't been migrated.
* Add scripts to create dumps and copy to MusicBrainz FTP (ftp://ftp.musicbrainz.org/pub/musicbrainz/bookbrainz)
* Setup dockerfile with changes for the new cron service
Not much really, but the bookbrainz.org/dumps/latest.bz2 link will need to redirect to ftp now.
=> Setup cron and regular data dumps for hetzner

src/client/entity-editor/common/new-date-field.js, src/client/entity-editor/edition-section/edition-section.js
https://tickets.metabrainz.org/browse/BB-347
Error thrown when creating a new edition from a work page resulting in a 500 error
=> fix: Fix BB-347 remedy null date for Editions without a releaseDate

src/client/containers/layout.js
fix(static): Fixed the Navigation bar buttons (eg. Add button) staying highlighted after clicking on them the second time
Added a method to prevent default behavior related to the focus on clicking a button.
Layout component which is in the layout.js file
=> fix(static): Fixed the Navigation bar buttons (eg. Add button) staying highlighted after clicking on them the second time

src/client/components/pages/parts/editor-achievements.js, src/client/controllers/editor/achievement.js, src/server/routes/editor.js
**Issue [BB-360](https://tickets.metabrainz.org/browse/BB-360)**: AchievementsTab Badges on Editor page doesn't work
Add **isOwner** boolean to check the owner.
- src/client/components/pages/parts/editor-achievements.js
- src/client/controllers/editor/achievement.js
- src/server/routes/editor.js
=> fix(profile): Fix AchievementsTab Badges on editor page [BB-360]

src/client/components/pages/contribute.js
Fix typo and update _programming skills list_ (Python)
Contibution page- src/client/components/pages/contribute.js
=> docs(static): fix typo and update programming skills in contribution page

README.md
Note on Webpack watch resource consumption.
README.md
=> docs: Add note on webpack-watch resource consumption

CONTRIBUTING.md
Missing info about forking and cloning in the CONTRIBUTING.md file
Added steps for Forking and Cloning the repository in CONTRIBUTING.md
CONTRIBUTING.md
=> docs: Added Forking and Cloning to CONTRIBUTING.md

src/server/templates/target.js
The word "undefined" appears on error pages.
Checks variables to make sure that "undefined" does not appear on error pages.
=> fix : removing "undefined" text at the bottom of error pages

src/client/components/pages/entities/author.js
https://tickets.metabrainz.org/browse/BB-369
Migrating the icons used on BookBrainz to official react-fontawesome package icons
Frontend
=> BB-369 - FontAwesome migration

src/client/components/forms/deletion.js
Migrate the icons used to official react-fontawesome package icons for the deletion.js file.
=> Migrate React-FontAwesome icons for deletion.js

src/client/components/pages/entities/edition-table.js
Moved old React-FontAwesome to new one by updating import and wherever Icon is used in script.
Ticket B-363 and subtask-4 on JIRA.
=> Migrated React-FontAwesome icons on edition-table.js

src/client/entity-editor/submission-section/submission-section.js
[BB-390: Identifiers validation not working](https://tickets.metabrainz.org/browse/BB-390)
Pass `identifiersTypes` parameter to `validate()` function
src/client/entity-editor/submission-section/submission-section.js
=> fix(editor): Fix Identifiers validation not working - BB-390

src/common/helpers/error.js, src/server/helpers/entityRouteUtils.js, src/server/routes/entity/author.js, src/server/routes/entity/entity.js, src/server/routes/entity/publisher.js
https://tickets.metabrainz.org/browse/BB-337
It shouldn't be possible to save a revision with no changes
=> fix (editor) : Saving a revision with no changes BB 337

package-lock.json, package.json, src/server/helpers/achievement.js, src/server/helpers/middleware.js, src/server/helpers/search.js, src/server/helpers/utils.js, src/server/routes/editor.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/work.js, src/server/routes/revision.js
Updating BookshelfJs to version 1.x requires some changes overall in the codebase, most notable the absence of 'require' flag set to false, fetch and fetchAll now thrown an error.
Set explicitly if a result is required, and improve error management.
=> ORM update requires some changes

src/client/components/pages/entities/work-table.js
https://tickets.metabrainz.org/browse/BB-374
Migrating React-FontAwesome : entities/work-table.js
src/client/components/pages/entities/work-table.js
=> React fontawesome bb374

src/client/components/pages/parts/search-field.js
https://tickets.metabrainz.org/browse/BB-376
Migrating React-FontAwesome : parts/search-field.js
src/client/components/pages/parts/search-field.js
=> React fontawesome #bb376

src/client/entity-editor/alias-editor/alias-editor.js
Ticket BB-377 on JIRA
Migrating React-FontAwesome
=> Migrating React-FontAwesome BB-377

src/server/helpers/entityRouteUtils.js, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js
https://tickets.metabrainz.org/browse/BB-398
src/server/helpers/entityRouteUtils.js
src/server/routes/entity/author.js
src/server/routes/entity/edition-group.js
src/server/routes/entity/edition.js
src/server/routes/entity/publisher.js
src/server/routes/entity/work.js
=> Fix #BB398: add proper title in create and edit revision page

src/client/entity-editor/button-bar/alias-button.js
=> BB-378 Migrating React-FontAwesome

src/server/routes/entity/entity.js
When saving an entity, the last step is to reindex that entity on the search server.
This was currently not taking into account changes made to the aliases, such that if the default alias changed it wouldn't be reindexed with its new name.
Found where we were returning the current entity model instead of the model returned when calling `model.save(…`.
Since Bookshelf v1.x, the model is returned updated, so there's no need to call `.refresh` anymore.
However the relations (aliases) are not refreshed, so we call `.load` instead before returning that to `search.indexEntity`
Only the entity saving process in server/routes/entiy/entity.js
=> Fix BB-367: reindex entities (search) with updated aliases

src/client/containers/layout.js, src/client/stylesheets/style.less
https://tickets.metabrainz.org/browse/BB-119
I changed the colour of hamburger icon.
=> fix(nav-bar) : change the colour of hamburger button

package-lock.json, package.json, scripts/build-client-js.sh, src/client/components/forms/deletion.js, src/client/components/pages/entities/footer.js, src/client/components/pages/entities/work-table.js, src/client/components/pages/entity-revisions.js, src/client/components/pages/index.js, src/client/components/pages/parts/revisions-table.js, src/client/components/pages/parts/search-field.js, src/client/components/pages/revisions.js, src/client/controllers/error.js, src/client/controllers/revisions.js, src/client/entity-editor/alias-editor/alias-editor.js, src/server/helpers/achievement.js, src/server/helpers/error.js, src/server/helpers/middleware.js, src/server/helpers/search.js, src/server/helpers/utils.js, src/server/routes.js, src/server/routes/editor.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/work.js, src/server/routes/index.js, src/server/routes/revision.js, src/server/routes/revisions.js
https://tickets.metabrainz.org/browse/BB-372
Migrating React-FontAwesome : entities/footer.js
src/client/components/pages/entities/footer.js
=> React fontawesome #bb372

config/config.local.json.example, src/client/components/pages/entities/edition.js
https://tickets.metabrainz.org/browse/BB-371
Migrating React-FontAwesome : edition.js
src/client/components/pages/entities/edition.js
=> React fontawesome #bb371

src/client/components/pages/parts/editor-profile.js
https://tickets.metabrainz.org/browse/BB-375
Migrating React-FontAwesome : parts/editor-profile.js
src/client/components/pages/parts/editor-profile.js
=> React fontawesome #bb375

src/client/entity-editor/common/new-date-field.js
https://tickets.metabrainz.org/browse/BB-381
Replaced `FontAwesome` with `FontAwesomeIcon`
src/client/entity-editor/common/new-date-field.js
=> BB-381 change FontAwesome->FontAwesomeIcon

src/client/entity-editor/common/linked-entity.js
https://tickets.metabrainz.org/browse/BB-380
Replaced `Icon` with `FontAwesomeIcon`
src/client/entity-editor/common/linked-entity.js
=> BB-380 change FontAwesome->FontAwesomeIcon

src/client/entity-editor/edition-section/edition-section.js
https://tickets.metabrainz.org/browse/BB-383
Replaced Icon with FontAwesomeIcon
src/client/entity-editor/edition-section/edition-section.js
=> BB-383 replace Icon->FontAwesomeIcon for edition-section.js

src/client/input.js
https://tickets.metabrainz.org/browse/BB-385
Replaced `Icon` with `FontAwesomeIcon`
src/client/input.js
=> BB-385 replace Icon->FontAwesomeIcon

src/client/entity-editor/identifier-editor/identifier-editor.js
https://tickets.metabrainz.org/browse/BB-384
Replace `Icon` with `FontAwesomeIcon`
src/client/entity-editor/identifier-editor/identifier-editor.js
=> BB-384 change Icon->FontAwesomeIcon

src/client/entity-editor/button-bar/identifier-button.js
https://tickets.metabrainz.org/browse/BB-379
Replace `Icon` with `FontAwesomeIcon`
src/client/entity-editor/button-bar/identifier-button.js
=> BB-379 replace Icon->FontAwesomeIcon

src/client/components/pages/editor-revision.js, src/client/components/pages/index.js, src/client/components/pages/parts/revisions-table.js, src/client/components/pages/revisions.js, src/client/controllers/editor/editor.js, src/client/controllers/revisions.js, src/client/stylesheets/style.less, src/server/helpers/utils.js, src/server/routes/editor.js, src/server/routes/revisions.js
https://tickets.metabrainz.org/browse/BB-397
Added pagination and improved table in the editor/:id/revisions
src/client/components/pages/editor-revision
src/routes/editor
src/client/components/pages/parts/revision-table
=> Editor revisions table - #BB-397

src/client/components/loading-spinner.js
https://tickets.metabrainz.org/browse/BB-368
Replaced `Icon` with `FontAwesomeIcon` and changed corresponding  icon name
src/client/components/loading-spinner.js
=> Bb 368 migrating react font awesome prabal

NODEJS_SETUP.md, README.md
https://tickets.metabrainz.org/browse/BB-427
moved   "Watch files and live reload with Webpack"  to readme.md 
NODEJS_SETUP.md
README.md
=> improved documentation of hot-reloading on repo

src/client/helpers/entity.js, src/server/routes/editor.js, src/server/routes/entity/entity.js, src/server/routes/revisions.js
HTML page wasn't showing the title properly
I have added titles to the page to make it more readable
HTML code
=> HTML TITLE FIX

src/client/components/pages/index.js, src/client/helpers/props.js, src/server/routes/index.js
https://tickets.metabrainz.org/browse/BB-441
passed a addition props to IndexPage "isLoggedIn" to ensure the JOIN US section shows only when the flag is set to false .
src/client/components/pages/index.js
src/client/controllers/index.js
=> fixed the unnecessary JOIN Us section when user is logged In 

src/client/components/pages/help.js
fix #BB-442. Corrected the numbering on help page
=> Fix(help): issue BB-442

package-lock.json, package.json, src/server/helpers/revisions.js, src/server/helpers/utils.js, src/server/routes/editor.js, src/server/routes/index.js, src/server/routes/revisions.js, test/src/server/helpers/revisions.js, test/test-helpers/create-entities.js
This PR is about having all the functions required for RevisionsPage, EditorRevisions, EntityRevisions inside routes/helper/revisions
And also write unit tests for these functions
=> Refactoring revision components

src/common/helpers/error.js, src/server/helpers/middleware.js, src/server/routes/entity/entity.js
https://beta.bookbrainz.org/work/123123
It'd be better if this page shows `Work not found error` rather than `Page not found`
Throw error even when `bbid` is invalid
src/server/helpers/middleware.js
=> Invalid bbid error

sql/migrations/2020-04-18/add_identifier.sql
BB-438, publisher identifier 
Add a .sql file in sql/migration/.. for adding identifier
Database
=> BB-438: VAIF id for publisher

.babelrc, package-lock.json, package.json
Warning message in console when building the client JS
Follow guidelines to use core-js
Webpack/babel build
=> chore(babel): Fix core-js warning when building client js

sql/migrations/user-collection/down.sql, sql/migrations/user-collection/up.sql, sql/migrations/user-collection/usercollection.sql, sql/schemas/bookbrainz.sql
Adding tables for UserCollection
=> Usercollection add tables

sql/scripts/delete_duplicate_relationships.sql
https://tickets.metabrainz.org/browse/BB-292
Some entities show multiple times the same relationship. This is probably caused by https://tickets.metabrainz.org/browse/BB-453
This script finds exactly equal relationships appearing in the same relationshipSet and deletes them.
Database
=> BB-292 fix(sql): Script to delete duplicate relationships

src/client/components/forms/profile.js, src/client/components/input/entity-search.js, src/client/components/pages/parts/search-field.js, src/client/components/pages/search.js, src/client/entity-editor/common/entity-search-field-option.js, src/client/entity-editor/name-section/actions.js, src/client/helpers/entity.js, src/server/helpers/search.js, src/server/routes/editor.js, src/server/routes/register.js, src/server/routes/search.js
Added `Editor` in the search result
=> search: add 'editor' type in the search result

sql/migrations/user-collection/up.sql, sql/schemas/bookbrainz.sql
Added primary key in item and collaborator tables
=> add primary key in usercollectionItem and usercollectionCollaborator 

src/server/routes/entity/entity.js
https://tickets.metabrainz.org/projects/BB/issues/BB-464
Entities we not reindex properly if alias changed
=> BB-464 fix: Reindex aliases properly on entity edit

src/client/entity-editor/common/entity-search-field-option.js
See https://tickets.metabrainz.org/projects/BB/issues/BB-401
=> fix BB-401: Full BB URL should trigger entity search

src/server/routes/entity/entity.js
Follow-up from PRs #407, #362 and #330
Fourth time trying to solve the issue !
What happened was that both the issue and the solution were not the same for new entities and existing entities being edited.
This PR *finally* fixes the issue properly.
=> fix BB-494: Search indexing fixed for new and edited entities

sql/migrations/user-collection/up.sql, sql/schemas/bookbrainz.sql, src/server/helpers/collectionRouteUtils.js
Changed `user_collection_collaborator.editor_id` --> `collaborator_id`
=> Db editor id collaborator

src/client/components/pages/collections.js, src/client/components/pages/entities/author.js, src/client/components/pages/entities/edition-group.js, src/client/components/pages/entities/edition.js, src/client/components/pages/entities/footer.js, src/client/components/pages/entities/publisher.js, src/client/components/pages/entities/work.js, src/client/components/pages/parts/add-to-collection-modal.js, src/client/components/pages/parts/collections-table.js, src/client/helpers/props.js, src/client/stylesheets/style.less, src/server/helpers/auth.js, src/server/routes/collection.js
Add Entity To Collection From Entity Page
1. Changed all entityPage to React Class
2. Added `Add To Collection` Modal
3. Created POST `collection/:collectionId/add` route
=> Add entity to collection entity page

src/client/components/pages/parts/search-field.js
Show collection in dropdown of searchField
=> show collection in dropDown list of searchField

src/client/components/pages/parts/add-to-collection-modal.js, src/client/components/pages/parts/search-results.js, src/client/components/pages/search.js, src/client/controllers/search.js, src/client/stylesheets/style.less, src/server/routes/search.js
UserCollection: Add to collections from search results
1. Changed the `result-table` to react class
2. Added checkboxes feature
=> UserCollection: Add to collections from search results

src/client/entity-editor/entity-merge.js, src/client/stylesheets/style.less, src/server/routes/merge.js
Annotations are currently being deleted during merge operations.
https://tickets.metabrainz.org/browse/BB-507
CSS could be improved for annotations
https://tickets.metabrainz.org/browse/BB-506
=> Annotations fixes

src/common/helpers/search.js
Users expect that disambiguation text  should be searchable.
We replace the single name search with a combined name + disambiguation fields search.
=> feat(BB-533): Add disambiguation to searchable fields

INSTALLATION_TROUBLESHOOTING.md, config/config.json.ctmpl, config/config.json.example, config/config.local.json.example, config/test.json, package-lock.json, package.json, src/common/helpers/search.js
- [BB-446](https://tickets.metabrainz.org/browse/BB-446): Update deprecated javascript client for ElasticSearch
- [BB-350](https://tickets.metabrainz.org/browse/BB-350): Autocomplete gives results that don't seem related
- [BB-219](https://tickets.metabrainz.org/browse/BB-219): All areas are now indexed, not just countries.
- Updated JS package and related configuration files
- Improved the autocomplete indexing and search configuration
- Figured out how to configure timeouts for local development, the blocking factor to indexing all areas
=> Search configuration improvements

package-lock.json, package.json
Updgrades node-postgres dependency causing issues on new LTS node version (used in CI)
=> chore: Update bookbrainz-data package

package-lock.json, package.json, src/common/helpers/search.js
As it says on the tin; index and display all Area search results (not just countries as it currently stands) along with their type and the other areas they are part of (city - subdivision - country):
=> Display all areas in search

.github/PULL_REQUEST_TEMPLATE.md
Incorrect order of number in PR Template
1
1
1
It should  be
1
2
3
=> [DOCS] : Fixed PULL_REQUEST_TEMPLATE

src/client/components/pages/parts/collections-table.js
This PR Fixes: [BB-593](https://tickets.metabrainz.org/projects/BB/issues/BB-593?filter=allopenissues)
Added margin to buttons
[collections-table.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/pages/parts/collections-table.js)
=> FIX(BB-593): Overlapping buttons

src/client/components/forms/profile.js
Fix bug where profile page does not load due to undefined area
Added undefined check on area
=> fix(profile): Fix bug where profile page does not load due to undefined area (BB-600)

src/client/stylesheets/style.less
Closes BB-605
Unlocked and Locked achievements are not visible on small screen devices
fixes badges visibility in editor's achievements tab
=> fixes badges visibility in editor's achievements tab

src/server/routes/editor.js
**This PR Fixes: [BB-468](https://tickets.metabrainz.org/browse/BB-468)**
Now the name in the navbar is updated whenever we edit our name in editor profile.
https://user-images.githubusercontent.com/55311336/113746625-29277280-9724-11eb-9300-a3fd22c77339.mp4
[server/routes/editor.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/server/routes/editor.js)
=> FIX(editor): Update username in navbar after update in editor profile

src/client/components/entity-link.js, src/client/components/pages/revision.js
updated **propTypes** and fixed invalid DOM property warning
- [components/entity-link.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/entity-link.js)
- [pages/revision.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/pages/revision.js)
=> FIX: proptypes mismatch and invalid DOM property warning

src/client/components/forms/userCollection.js, src/client/components/pages/entities/footer.js, src/client/components/pages/parts/add-entity-to-collection-modal.js, src/client/entity-editor/alias-editor/alias-row-merge.js, src/client/entity-editor/common/make-immutable.tsx, src/client/entity-editor/edition-section/reducer.ts, src/client/entity-editor/relationship-editor/relationship-editor.tsx, src/client/entity-editor/validators/base.ts
stale imports should be removed.
Refactored
components/forms/userCollection.js
components/pages/entities/footer.js
components/pages/parts/add-entity-to-collection-modal.js
entity-editor/alias-editor/alias-row-merge.js
entity-editor/common/make-immutable.tsx
entity-editor/edition-section/reducer.ts
entity-editor/relationship-editor/relationship-editor.tsx
entity-editor/validators/base.ts
=> chore: removed all the stale imports

src/client/components/pages/parts/search-results.js, src/common/helpers/search.js
This PR Fixes: [BB-619](https://tickets.metabrainz.org/browse/BB-619)
Filter out all the private collections before showing in the search results. 
- [helpers/search.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/common/helpers/search.js)
=> [BB-619]: Search results should not contain private collections

src/client/containers/layout.js
This PR replaces #584, as it looks like the fork repository the PR originates from does not exist anymore.
=> (BB-599): Added revisions, achievements and collections in user dropdown in navbar

src/client/entity-editor/common/entity-search-field-option.js, src/client/entity-editor/relationship-editor/relationship-editor.tsx
This PR Fixes: [BB-454](https://tickets.metabrainz.org/browse/BB-454)
Filtered the search field options using entity bbid
- [common/entity-search-field-option.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/entity-editor/common/entity-search-field-option.js)
- [relationship-editor.tsx](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/entity-editor/relationship-editor/relationship-editor.tsx)
=> BB-454: Should not be able to create relationship with itself

src/client/components/forms/deletion.js, src/client/components/pages/about.js, src/client/components/pages/contribute.js, src/client/components/pages/help.js, src/client/components/pages/index.js
Moving from Freenode to Libera.Chat
=> docs: Update IRC channel information

src/client/entity-editor/entity-merge.tsx
Regression from PR #606 where I changed the HTML form functionality and moved the submission action to the topmost <form> element in the entity editor, but I forgot to change it in the merge editor as well.
=> Fix: Merge editor submit action

src/client/entity-editor/entity-merge.tsx, src/server/routes/entity/entity.tsx
Entity deletion seems to be partly broken, in particular the interaction with the method that deletes the entity from the search index.
Some changes we made on part of the codebase and the delete method was forgotten.
=> Fix deletion handler

src/client/components/forms/userCollection.js, src/client/components/pages/collection.js, src/client/components/pages/entities/series-table.js, src/client/components/pages/parts/search-results.js, src/client/helpers/utils.tsx, src/server/routes/collection.js
- Created SeriesTable component.
- Extended collections to include series entity.
=> feat(collection,series): Extend Collection to include Series Entity.

src/server/routes/entity/series.js
Implemented Deletion Handler for series entity.
=> feat(series): deletion handler

test/src/server/routes/entity/series.js, test/test-helpers/create-entities.js
=> test(series): add tests for main GET routes

src/api/helpers/formatEntityData.ts, src/api/routes.js, src/api/routes/series.js
**Added lookup endpoints for series:**
=> API: add lookup endpoints for series

src/server/routes/editor.js
This PR Fixes: [#627](https://tickets.metabrainz.org/projects/BB/issues/BB-627)
Two response were sent to the client side upon a request leading to **Uncaught Exception: Error [ERR_HTTP_HEADERS_SENT]  Cannot set headers after they are sent to the client**
First Response :
https://github.com/bookbrainz/bookbrainz-site/blob/66a1b8706579eb1bfa8b598e0071bf239c408fa9/src/server/routes/editor.js#L506
Second Response:
https://github.com/bookbrainz/bookbrainz-site/blob/66a1b8706579eb1bfa8b598e0071bf239c408fa9/src/server/routes/editor.js#L511
https://github.com/bookbrainz/bookbrainz-site/blob/66a1b8706579eb1bfa8b598e0071bf239c408fa9/src/server/helpers/handler.js#L27
return the response statement and refactor code.
https://github.com/bookbrainz/bookbrainz-site/blob/66a1b8706579eb1bfa8b598e0071bf239c …
=> FIX(BB-627): set badges in achievement section

sql/migrations/series-identifiers/down.sql, sql/migrations/series-identifiers/up.sql, src/client/components/pages/entities/identifiers-links.js
**Summary** 
Added identifiers for series.
=> feat(series): add identifiers

sql/migrations/series-achievement/down.sql, sql/migrations/series-achievement/up.sql, src/server/helpers/achievement.js
**Summary:**
Added achievement for series creation.
=> feat: add achievement for series creation

src/client/entity-editor/relationship-editor/relationship-editor.tsx
**Summary:**
When the base entity is a Series, we need to filter out relationshipType 70 - 74. As this relationships will be added via the series editor, we don't want to show them in the relationship modal.
=> filter relationships when baseEntity is Series

src/client/entity-editor/relationship-editor/relationship-editor.tsx, src/client/entity-editor/relationship-editor/relationship-section.tsx
**Summary:**
Set relationship attributes value in relationship-editor.
=> feat: set relationship attributes value in relationship-editor

src/client/entity-editor/series-section/actions.ts, src/client/entity-editor/series-section/reducer.ts, src/client/entity-editor/series-section/series-editor.tsx, src/client/entity-editor/series-section/series-section.tsx, src/server/helpers/middleware.ts, src/server/routes/entity/series.js
**Summary:**
- Added drag and drop feature to order the items in the series in any way you want.
=> feat(series): drag and drop to order series items.

src/client/entity-editor/helpers.ts, src/client/entity-editor/series-section/series-section-merge.tsx, src/server/helpers/merge.js, src/server/helpers/middleware.ts, src/server/helpers/utils.ts, src/server/routes/entity/series.js, src/server/routes/merge.ts
**Summary**
Created Merging tool for Series.
=> feat: Series Entity Merging Tool 

src/client/components/pages/entities/identifiers.js
BB-511 : Consistently sort identifiers
sort the identifiers alphabetically
1. src/client/components/pages/entities/identifiers.js
=> Fix[BB-511]: sorted identifiers alphabetically

src/client/components/pages/entities/edition.js
Physical data section should be disabled if eBook is chosen
=> [BB-622]: Remove dimensions if format is eBook

src/server/routes/entity/entity.tsx
BB-635: Website crashes due to not handling already deleted entity case.  
return 409 response code
1. src/server/routes/entity/entity.tsx
=> Fix[BB-635]: adding check for deleted entity

src/client/components/pages/collections.js, src/client/components/pages/parts/collections-table.js, src/server/routes/collections.js
BB-610: In collections page, entity type URL parameters don't work on refresh or navigation
use query params to show correct label in dropdown.
1. src/client/components/pages/collections.js
2. src/client/components/pages/parts/collections-table.js
3.  src/server/routes/collections.js
=> Fix(BB-610): Using query params to show correct label in dropdown

src/client/components/footer.js, src/client/components/forms/deletion.js, src/client/components/forms/parts/achievement.js, src/client/components/forms/profile.js, src/client/components/forms/registration-details.js, src/client/components/forms/userCollection.js, src/client/components/pages/about.js, src/client/components/pages/contribute.js, src/client/components/pages/develop.js, src/client/components/pages/help.js, src/client/components/pages/index.js, src/client/components/pages/licensing.js, src/client/components/pages/parts/call-to-action.js, src/client/components/pages/parts/editor-achievements.js, src/client/components/pages/parts/search-field.tsx, src/client/components/pages/parts/search-results.js, src/client/components/pages/privacy.js, src/client/components/pages/registration-auth.js, src/client/components/pages/statistics.js, src/client/containers/layout.js, src/client/input.tsx, webpack.client.js
Review time estimate: 20 minutes
There are a number of issues which it's helpful to resolve before moving the site from Bootstrap 3 to Bootstrap 4.
Before submitting the PR that moves to BS4, this PR addresses these issues, fixing a few UI bugs, speeding up webpack compilation time and cleaning up unused code.
Client components and webpack configuration. Excluding whitespace changes, the largest diffs are to src/client/components/forms/userCollection.js and src/client/components/pages/licensing.js.
=> Prepare client components for bootstrap 4

.github/config.yml, CONTRIBUTING.md, INSTALLATION_TROUBLESHOOTING.md, README.md, src/client/components/pages/contribute.js, src/client/components/pages/develop.js, src/common/helpers/config.js, src/server/app.js
Updating links after transferring ownership of the repository to the MetaBrainz organization.
Also taking this opportunity to update some badges on the readme, as some were outdated or not working anymore.
=> Update repository information and links

src/server/routes/editor.js
while working on react-select in profile, i realized changing gender in editor doesn't considered as change thus giving no change error, i added check for the same in editor route.
=> Fix(editor): Add comparision for genderId

src/server/routes/editor.js
Since function execution doesn't stop after next(err) thus causing issues
Relevant ticket BB-651: 502 when trying to load an editor by name
editor route
=> Fix(BB-651): Error handling for not found editor

.github/workflows/ci.yml, package.json, test/src/api/routes/test-publisher.js, test/src/server/routes/entity/edition.js, test/test-helpers/create-entities.js, yarn.lock
Improve test helper for publisher creation, using single PublisherType for each publisher.
=> Improve test helpers for creating Publisher

package.json, src/client/components/pages/entities/cb-review.js, src/client/components/pages/entities/edition-group.js, src/client/components/pages/entities/links.js, src/client/components/pages/entities/related-collections.js, src/server/helpers/critiquebrainz.ts, src/server/helpers/middleware.ts, src/server/routes.js, src/server/routes/externalService.js, src/server/routes/reviews.js, yarn.lock
This PR adds CritiqueBrainz reviews for EditionGroup.
=> feat(editionGroup): Show CB reviews for Edition Group

src/client/components/author-credit-display.js
I made a rookie mistake in #868 !
Fixing it before deploying beta.
=> fix(AC): Fix author credits display

src/client/components/pages/parts/call-to-action.js
Relevant ticket [BB-682](https://tickets.metabrainz.org/projects/BB/issues/BB-682): Make Create entity buttons real links
=> BB-682: Use plain links in call-to-action buttons

src/client/entity-editor/edition-section/reducer.ts
Do not add null language to edition languages.
=> Fix(UF): Selecting Language crashes the site

.vscode/launch.json
There is no configuration available for debugging the server running in a Docker container using vscode.
This PR will add a config set up in launch.json file for debugging in Docker container
Only .vscode/launch.json file
=> Docker config for vscode debugging console

src/client/helpers/utils.tsx
Its an extension of the ticket https://tickets.metabrainz.org/browse/BB-662
I fixed the the link so that it opens in new tab.
utils.tsx in helpers
=> BB-662 (II): Links don't open in new tab

src/server/routes/merge.ts
[BB-675](https://tickets.metabrainz.org/browse/BB-675): 
Across the codebase we have asynchronous code written using promises, which is hard to read and to maintain and error-prone.
All this code was rewritten using the async/await syntax.
The changes were reflected in  `src/server/routes/merge.ts`
=> BB-675: Rewrite merge routes using async/await syntax

.github/workflows/ci.yml, scripts/create-test-db.sh
Changed in the config files but not in the test DB script, see 814d07b3161908e82127b9ef53c04751dd20c77f.
=> chore: update host and user of the test DB

config/config.local.json.example, src/server/app.js
Test or beta site requires a distinguishing banner to differentiate it from Bookbrainz site
Added a banner to distinguish test or beta site
=> BB-563: Added banner to give test.bb.org a distinguishing feature

src/client/components/forms/registration-details.js, src/client/entity-editor/author-credit-editor/author-credit-section.tsx, src/client/entity-editor/author-section/author-section.tsx, src/client/entity-editor/common/entity-select.tsx, src/client/entity-editor/common/language-field.tsx, src/client/entity-editor/common/linked-entity-select.tsx, src/client/entity-editor/edition-group-section/edition-group-section.tsx, src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/publisher-section/publisher-section.tsx, src/client/entity-editor/relationship-editor/relationship-select.tsx, src/client/entity-editor/work-section/work-section.tsx, src/client/helpers/entity.tsx, src/client/helpers/utils.tsx, src/server/helpers/middleware.ts, src/server/routes/merge.ts
BB-732
Fixed 85 linter errors that stopped the testing suite from running
All, no behaviours changed
=> BB-732: fix for linter errors on testing suite

sql/migrations/2023-05-15-work-types/up.sql, sql/schemas/bookbrainz.sql, src/client/entity-editor/work-section/work-section.tsx, src/client/stylesheets/style.scss, test/test-helpers/create-entities.js
The list was short, now it is long.
Thanks to the great community effort at https://community.metabrainz.org/t/work-types-proposal/627587 we have a new list of Work entity types with a hierarchy.
Two parts to this PR:
1. A big'ol SQL migration script to add the required columns, modify existing work types and add new ones
2. Some work done on the work type select dropdown to show the hierarchy and a tooltip with the description:
=> BB-740: Extend and improve the list of work types

src/common/helpers/privileges-utils.ts, src/common/helpers/session.ts, src/server/helpers/auth.ts, src/server/helpers/utils.ts, src/server/routes/adminPanel.tsx, src/server/routes/editor.tsx, src/server/routes/entity/author.ts, src/server/routes/entity/edition-group.ts, src/server/routes/entity/edition.ts, src/server/routes/entity/entity.tsx, src/server/routes/entity/publisher.ts, src/server/routes/entity/series.ts, src/server/routes/entity/work.ts, src/server/routes/merge.ts, src/server/routes/reviews.ts, src/server/routes/unifiedform.ts, src/server/routes/wikimedia.ts, test/src/server/routes/editor.js
This PR is a followup to the previous [PR](https://github.com/metabrainz/bookbrainz-site/pull/999), and it specifically addresses the points raised [here](https://github.com/metabrainz/bookbrainz-site/pull/999#discussion_r1252176292).
=> feat(Admin System): Improve type validation with TypeScript

package.json, src/client/components/footer.js, src/client/components/pages/adminLogs.js, src/client/components/pages/adminLogs.tsx, src/client/components/pages/parts/admin-log-statement.js, src/client/components/pages/parts/admin-logs-table.js, src/client/components/pages/parts/privs-edit-modal.js, src/client/controllers/adminLogs.js, src/client/helpers/adminLogs.tsx, src/client/stylesheets/style.scss, src/common/helpers/privileges-utils.ts, src/server/helpers/adminLogs.ts, src/server/helpers/utils.ts, src/server/routes.js, src/server/routes/adminLogs.tsx, src/server/routes/adminPanel.tsx, src/server/routes/editor.tsx, test/src/server/routes/editor.js, webpack.client.js, yarn.lock
This PR adds an Admin logs page.
I have also added a field for adding a note/reason in the privs-edit-modal.
=> feat(Admin System): Admin logs page

src/server/routes/auth.js
The users are currently redirected to home page after login.
This PR fixes this issue by redirecting the users to their original link they desire.
=> fix: Redirect users after login

src/client/components/input/drag-and-drop-image.tsx, src/client/components/pages/revision.js, src/client/entity-editor/work-section/work-section.tsx, src/client/helpers/utils.tsx, src/client/unified-form/submit-tab/summary.tsx, src/server/helpers/diffFormatters/authorCredit.ts, src/server/routes/search.js
Simple fixes.
There are two warnings left regarding todos that would need to be fixed in a separate PR  (the "do" in "todo")
=> Fix linting errors and warnings

src/client/helpers/utils.tsx
- Updated the urlRegex to match URLs in text.
- Added function with O(n) time complexity to count and remove trailing parantheses.
BB-779
Updated the urlRegex and also added a function with O(n) time complexity to count and remove trailing parantheses from a URL string.
The changes were reflected in src/client/helpers/utils.tsx
=> BB-779:URLs with parentheses don’t parse

src/common/helpers/search.js
I can't figure out why indexing is failing for new works created on prod (not on test.BB nor on local dev…), but at least I can prevent the site from crashing!
=> fix(search): Catch search indexing errors

src/client/components/pages/about.js, src/client/components/pages/index.js
BB-791
1- changed the icon and name of Twitter to X on the index page and about us.
2- changed the X "Twitter" link  to the correct link for the bookbrainz account, the link was wrong before
`src/client/components/pages/index.js`
`src/client/components/pages/about.js`
=> fix(profile): change Twitter to X

src/client/entity-editor/author-credit-editor/author-credit-section.tsx
BB-782
problem : https://github.com/metabrainz/bookbrainz-site/pull/1071#issuecomment-2131320382
WARNING⚠️ : HUGE NUMBER OF CHANGES IN LINES OF CODE
author credit section
=> fix BB-782 : Unable to edit Author Credit after having set it

package.json, yarn.lock
Fixes https://github.com/metabrainz/bookbrainz-site/security/dependabot/70
=> chore: Update DOMPurify

package.json, yarn.lock
Fixes security issue https://github.com/metabrainz/bookbrainz-site/security/dependabot/74
=> chore: update Superagent
