metabrainz/bookbrainz-site

package.json, src/server/helpers/auth.js
The -site side of the bcryptification of -data-js. Depends on bookbrainz/bookbrainz-data-js#1.
=> Shift the burden of hash/salt handling to -data-js

src/client/components/forms/edition.jsx, src/client/components/forms/parts/editionData.jsx, src/client/components/forms/parts/workData.jsx, src/client/components/input/entity-search.jsx, src/server/helpers/diffFormatters/base.js, src/server/helpers/diffFormatters/entity.js, src/server/helpers/diffFormatters/languageSet.js, src/server/helpers/diffFormatters/publisherSet.js, src/server/helpers/diffFormatters/releaseEventSet.js, src/server/helpers/diffFormatters/set.js, src/server/helpers/search.js, src/server/routes/entity/creator.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js, src/server/routes/revision.js, templates/entity/view/edition.jade, templates/entity/view/publication.jade, templates/entity/view/publisher.jade, templates/entity/view/work.jade
There are two major changes wrapped up in this branch: one, the changes directly related to the entity set implementation in -sql and -data-js, which covers pulling in the model relations that were set up and appropriately changing references; and two, changes to editing to both accommodate and take advantage of these changes. This allows entity editing to be much more generic and, as a major bonus, more easily calculate whether there are changes during editing that necessitate a new revision.
N.B.: While the bulk of these changes have been tested reasonably thoroughly, Edition and Work creation and editing need testing and a general smoketest is needed to make sure that nothing else broke horribly.
=> Pull in entity data set schema changes

src/server/routes/index.js
This just constrains Recent Activity to only fetch master revisions.
=> Don't list duplicate entities under Recent Activity

src/server/routes/entity/creator.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js, src/server/routes/relationship/edit.js
Many routes do not use the correct authentication middleware. Namely, the relationship editor and delete handler routes do not require authentication and handlers were not correctly adapted to use the handler-specific auth route.
Survey all routes and set correct authentication middleware.
Route authentication for relationship editing, entity deletion, and entity create/edit.
=> BB-191 Use correct authentication middleware everywhere

data/testData.js, src/client/components/forms/profile.jsx, src/server/helpers/achievement.js, src/server/routes/editor.js, test/testAchievement.js, test/testCreatorCreator.js, test/testLimitedEdition.js, test/testPublisher.js, test/testPublisherCreator.js, test/testSprinter.js, test/testWorkerBee.js
Old achievements were based on number of revisions performed, this meant someone could simply revise the same entity multiple times to get the achievement.
Old version used Select component rather than Select2 component in edit profile
Base the achievements on creation of entities
Add Worker bee and Publisher creator achievements
Convert edit profile to Select2 component
Achievement module
Edit Profile form
Editor Route
Achievements tests
=> Creation achievements

src/server/helpers/search.js
Bringing up a new instance of BookBrainz currently requires the administrator to manually hit `/search/reindex`.
When starting the BB instance, verify that the search index exists. If not, generate it.
Server boot, search index generation.
=> Generate search index automatically on server boot

src/client/components/forms/publication.js, src/server/helpers/utils.js
Lack of documentation makes maintaining the project harder and puts a higher bar of entry for new developers.
Adds JSDoc style annotations to a few files in the codebase, outlining the purpose, params, and return values.
Annotations should not alter the behaviour of any existing code.
=> Added JSDoc annotations - GCI

src/client/components/forms/creator.js, src/client/components/forms/parts/creator-data.js, src/client/components/forms/parts/publisher-data.js, src/client/components/forms/parts/relationship-row.js, src/client/components/forms/profile.js, src/client/components/forms/publisher.js, src/client/components/forms/relationship.js, src/client/components/input/entity-search.js, src/server/helpers/search.js, src/server/routes/editor.js, src/server/routes/entity/creator.js, src/server/routes/entity/publisher.js
The site does not include a way to modify location-based fields.
- Allows EntitySearch component to have its search narrowed down to a particular collection
- Builds on top of the existing schema support for areas to add additional area input components into forms that require it. Also modifying the data sent up to the server to include the results from the new inputs.
- Modifies the server-side entity edit handlers to accept the new area fields
- Adds area relations into a few indexed entity models
This PR affects a few client-side forms, server indexing code, and entity edit handlers.
- Current indexing code is buggy
- Error is thrown when edit handler of Creator entity is requested without any of its data being changed (successfully replicated on live site).
- **UPDATE**: is this …
=> Updated forms and server to support area editing

src/client/components/forms/parts/creator-data.js, src/client/components/forms/parts/publisher-data.js, src/client/components/forms/profile.js, src/client/components/input/entity-search.js, src/client/components/pages/parts/search-results.js, src/client/helpers/utils.js, src/server/helpers/search.js, src/server/helpers/utils.js, src/server/routes/editor.js
Area entities are not being indexed; hence EntitySearch components included in #114 have no way of providing any area options to user. The Area entity is different from the other indexed entities so some special cases need to be made. There are also some issues with data retrieval and insertion in the EntitySearch component.
Indexes the Area entity, patches data handling issues in EntitySearch, and adds special cases in search for dealing with Area entities. Also introduces a few styling touches such as disabling area links in the SearchPage results and a globe icon for area entities.
Impacts the indexing and some search functions, Creator, Publisher and Profile edit forms, SearchResults component.
=> area-fixes-Daniel-Hsing

src/client/components/pages/parts/editor-profile.js, src/server/helpers/diffFormatters/base.js, src/server/routes/revision.js, templates/editor/editor.jade, templates/entity/view/creator.jade, templates/entity/view/publisher.jade
Area information for Creator and Publisher entities and the editor are not being displayed on the site.
Adds area attributes to entity pages and profile pages of editors. Also updated server + model code in https://github.com/bookbrainz/bookbrainz-data-js to include area changes in entity revisions.
Minimal impact on Creator, Publisher, and Editor templates. Adds new cases to server-side revision code that is used to format changes for the client.
=> Added area information to UI

src/client/components/pages/entity-revisions.js, src/server/routes/entity/entity.js
Entity revision display is being rendered with pug instead of React.
Created a React component for displaying entity revisions. Updated server code to render the newly created component instead of the old template. Also included 'revision.notes' in the relations being fetched to the client.
Updates the displayRevisions render function and adds a new component to the client folder.
=> Entity revisions conversion - GCI

README.md
There was a typo in the server setup code in the README. The code snippet read:
```  sudo -u postgres  bookbrainz -c "SELECT name FROM bookbrainz.editor" ```
However typing this command into my terminal gave me 
```sudo: bookbrainz: command not found```.
This PR adds the command ```psql``` in front of ```bookbrainz``` so it will actually try to access the database.
New dev experience?
=> Fixed typo in README about checking successful database setup

src/client/components/forms/work.js
File src/client/components/forms/work.js had minimal documentation
beforehand. 
Added comments to clarify the purpose of the methods and
some bits of code that were ambiguous at first.
src/client/components/forms/work.js was changed. No behavior is affected.
I wasn't able to find the precommit hook but I attempted to remain consistent
with the coding style as I could.
(For GCI 2016-17)
=> Add documentation to WorkForm component

src/client/components/footer.js, templates/footer.jade
Currently, "Report a Bug" button in the footer doesn't link to MeB's bug tracker.
The fix was mostly simple, adding a link to the Jira Bug Tracker.
All webpages should now link to the bug tracker
=> Fix bug tracker link

package-lock.json, package.json, src/client/components/forms/profile.js, src/client/components/input/select-wrapper.js, src/client/components/pages/revision.js, src/client/entity-editor/common/language-field.js, src/client/entity-editor/validators/work.js, src/server/helpers/props.js, src/server/routes/editor.js, src/server/routes/entity/creator.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js, src/server/routes/index.js, src/server/routes/register.js, src/server/routes/revision.js, src/server/routes/search.js, templates/target.jade
Server-generated props were not being escaped properly which allowed for script injection to occur. This issue has been resolved using the [jsesc](https://github.com/mathiasbynens/jsesc) library which converts JS objects to strings and escapes characters according to specified options. 
**note:** once Jade/Pug templates are replaced with html string templates, validation/escape logic can be moved directly into the template file so the boilerplate added from this PR is a temporary measure.
=> Escape invalid characters in injected prop string

package.json, src/server/app.js
Server responses can be slow for people with low bandwidth. 
Adding the node "compression" module to compress all incoming responses.
=> fix: added compression middleware

src/client/components/pages/entity/creator.js, src/client/components/pages/entity/edition.js, src/client/components/pages/entity/publication.js, src/client/components/pages/entity/publisher.js, src/client/components/pages/entity/work.js, src/client/controllers/deletion.js, src/client/controllers/editor/achievement.js, src/client/controllers/editor/edit.js, src/client/controllers/editor/editor.js, src/client/controllers/entity/entity.js, src/client/controllers/index.js, src/client/controllers/registrationDetails.js, src/client/controllers/revision.js, src/client/controllers/search.js, src/client/entity-editor/controller.js, src/client/helpers/props.js, src/server/helpers/error.js, src/server/routes/editor.js, src/server/routes/entity/creator.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js, src/server/routes/index.js, src/server/routes/register.js, src/server/routes/revision.js, src/server/routes/search.js
server-side dependencies such as `jsesc` were previously being pulled into the client bundle and not being transpiled properly. This patch should prevent this from happening.
=> fix: separate server-only prop helpers from isomorphic prop helpers

src/client/components/input/select-wrapper.js
Previously, some props being passed to the base select component (such as the critical `onChange` prop) were being overridden by null values from the component's `defaultProps` property. As a result, some select components on the site (i.e. the gender select input) were not functional. This change fixes this behavior by ensuring that the named props always overrides the default ones. 
Another way of addressing this issue would have been to remove unnecessary `defaultProps` values.
=> fix: add spread props before named props in select-wrapper component

test/common.js, test/test-creator-creator.js, test/test-explorer.js, test/test-fun-runner.js, test/test-hot-off-the-press.js, test/test-limited-edition.js, test/test-marathoner.js, test/test-publisher-creator.js, test/test-publisher.js, test/test-revisionist.js, test/test-sprinter.js, test/test-time-traveller.js, test/test-worker-bee.js
Reduce the amount of code that needs to be maintained for testing.
Factor out common assertion pattern applied to `achievementPromise`.
This affects most `.js` files directly in the `test/` directory and doesn't change any behaviour.
=> refactor(tests): Eliminate some code duplication

src/client/components/forms/registration-details.js
Make the CI tests pass.
Revert changes mistakenly not reverted in 0930e7d.
Only `src/client/components/forms/registration-details.js` is affected.
No behaviour changes.
=> fix(registration): fix CI error from 0930e7d

package.json
Linter errors aren't being caught when committing.
Adds a pre-commit hook that runs `eslint` on all staged `*.js` files, and does
not allow you to commit until errors are fixed.
Only the `package.json` (and of course the `package-lock.json`) is affected.
By the way, the branch is named `precommit-eshansingh` because my GCI username is Eshan Singh, as it's forced to be my real name, but my GH username is different.
=> Add eslint precommit hook

src/server/helpers/utils.js, src/server/routes/entity/creator.js, src/server/routes/entity/edition.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js
We have provision in the database for making identifier types specific to entity type, but this is unused. As such, it is possible to set the ISBN of a Creator, which does not make sense.
Before passing identifier types to the editor component, filter them by entity type. To allow users to edit existing identifiers which have been mistakenly added to the wrong entity type, the types of any existing identifiers are added on the edit page.
Entity creation and editing.
**NOTE**: The following script should be run to migrate existing data to use appropriate entity types: https://gist.github.com/leftmostcat/b2d91955769831887b0b28f0f13db40c
=> Filter identifier types by entity type

.jsinspectrc, package.json, src/client/components/pages/entities/creator.js, src/client/components/pages/entities/details.js, src/client/components/pages/entities/edition.js, src/client/components/pages/entities/links.js, src/client/components/pages/entities/publication.js, src/client/components/pages/entities/publisher.js, src/client/components/pages/entities/work.js, src/client/entity-editor/validators/common.js, src/server/helpers/entityRouteUtils.js, src/server/routes/editor.js, src/server/routes/entity/creator.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js
_**NOTE**: This PR is #173, but all at once, with signed commits, and as such no coveralls spam. Will push less often next time 🙇_
Various instances of duplication. See current `dupreport`:
https://gist.github.com/naiveaiguy/1eb8a12f2aa75876a1729d6f0bff1c10
Originally 23 matches were there. Now there are only 12. 
Extracts methods that abstract out the functionality of these duplicates. I've tried as much as possible to keep each commit sensible and working, so any of these can be reverted individually relatively cleanly if the need arises. 
* package.json - `dupreport` script
* entity routes on server - unchanged behaviour - various extracted utils
* entity page on client - unchanged behaviour - `EntityDetail` component - *EDIT*: changed name to `EntityLinks`
* `editor` - unchanged …
=> Various duplication refactors

test/common.js, test/test-creator-creator.js, test/test-explorer.js, test/test-fun-runner.js, test/test-hot-off-the-press.js, test/test-limited-edition.js, test/test-marathoner.js, test/test-publisher-creator.js, test/test-publisher.js, test/test-revisionist.js, test/test-sprinter.js, test/test-time-traveller.js, test/test-worker-bee.js
Reduce the amount of code that needs to be maintained for testing.
Deduplicate common test patterns
This affects most `.js` files directly in the `test/` directory and doesn't change any behaviour.
=> refactor(tests): Deduplicate common test patterns

src/server/helpers/render.js, test/test-render-relationship.js
There's no documentation or tests for `renderRelationship`. 
Add documentation and tests. Maybe not the biggest issue, but I though it was useful to have some anyway. It was also good to get used to `mocha` and `chai`. Will make some more substantial tests after GCI.
No behaviour changes, only new tests and docs.
=> Add documentation and tests for renderRelationship

scripts/build-client-js.sh, scripts/watch-client-js.sh, src/client/components/pages/index.js, src/client/components/pages/statistics.js, src/client/containers/layout.js, src/client/controllers/statistics.js, src/server/routes.js, src/server/routes/statistics.js
Collective information of activities is not present on the website.
A statistics page is added.
scripts/build-client-js.sh
src/client/components/pages/index.js
src/client/components/pages/statistics.js
src/client/controllers/statistics.js
src/server/routes.js
src/server/routes/statistics.js
=> Add Statistics Page for top 10 editors

src/server/helpers/achievement.js, src/server/routes/editor.js
There is use of _.snakeCase on literal(editorId).
Remove use of _.snakeCase and use editor_id directly.
src/server/helpers/achievement.js
src/server/routes/editor.js
=> Remove unnecessary call of _.snakeCase on a literal

src/client/components/pages/revision.js
Remove log.debug from revision page to resolve
error: can not read property `readable` of undefined.
Fixes #245
Issue [BB-245](https://tickets.metabrainz.org/projects/BB/issues/BB-245?filter=allopenissues) 
Remove log.debug from revision page in the client side.
src/client/components/pages/revision.js
=> fix(client): remove logger from client side.

test/mocha.opts
Presently, tests are only run if they are direct children of test directory,
although there are some tests which lie in the subdirectory, like inside
test/src/client.
Trying to run the tests inside the subdirectories in the `test` folder.
Add `--recursive` flag to the `npm run test` script in package.json file.
package.json
=> BBS-254: fix(package.json) Run tests recursively in all the subfolders

.travis.yml
Fixes failing travis builds since [this commit to bookbrainz-sql](https://github.com/bookbrainz/bookbrainz-sql/commit/33425aeaedb003223a6b16276316562f17d80310#diff-699266fb29ba68cf5bb74045f6a50744R674), requiring version >= 9.4 of postgres to use jsonb
=> test(core): Added postgres version in travis config

flow-typed/npm/express_v4.16.x.js, package.json, src/client/entity-editor/common/entity-search-field.js, src/client/entity-editor/entity-editor.js, src/client/entity-editor/helpers.js, src/client/entity-editor/relationship-editor/actions.js, src/client/entity-editor/relationship-editor/reducer.js, src/client/entity-editor/relationship-editor/relationship-editor.js, src/client/entity-editor/relationship-editor/relationship-section.js, src/client/entity-editor/relationship-editor/relationship.js, src/client/entity-editor/relationship-editor/types.js, src/client/stylesheets/style.less, src/server/helpers/entityRouteUtils.js, src/server/helpers/middleware.js, src/server/helpers/render.js, src/server/routes/entity/creator.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js
There is no way to edit relationships in the site.
This PR consolidates the entity creation and editing code. It adds a client side relationship editor as part of the existing entity editor React app, and then adds functions to handle the new relationship data server-side, as part of the new entity creation and editing function. The relationship schema has also changed, so some updates are made to relationship rendering to deal with this.
The client-side entity editor, the server side entity revision handling code, and relationship rendering code.
=> New relationship editor

src/client/entity-editor/button-bar/button-bar.js, src/client/entity-editor/identifier-editor/value-field.js
Adds an empty identifier row whenever the Identifier Editor is opened.
Ticket [BB-271](https://tickets.metabrainz.org/browse/BB-271):
> If I click "Add identifiers" when editing an entity, "This entity has no identifiers" gives me nothing of use and just wastes my time by making me click Add identifier. Just give me an empty, ready to fill set of identifier fields - I can figure out that if there's nothing else there, there are no identifiers currently. At most, show both "This entity has no identifiers" and empty fields to change that.
Calls the addIdentifierRow action whenever the identifier button is pressed (the onIdentifierButtonClick function is called).
Only the file responsible for the buttons in the aliases/identifiers/disambiguations …
=> BB-271 - feat(button-bar): Preload the first (empty) identifier

src/client/entity-editor/identifier-editor/value-field.js, src/client/entity-editor/relationship-editor/relationship-editor.js
As desribed on [BB-272](https://tickets.metabrainz.org/browse/BB-272): 
> Once I've selected both an entity and a relationship type, letting me submit the form by just pressing Enter while on either of the fields would be a big time saver. After all, it's trivial to just edit / undo if I messed it up.
This creates a handle for keypresses, that calls the handleAdd handle whenever the "enter" key is pressed.
**Change from ticket criteria:**
While the ticket says that the enter key should submit the data anywhere in the form, I've made it only submit when on the second input box. This is because when selecting a user in the first input box, the enter key can be used to make your selection, which would thus close the Editor before the user has a chance to enter anything in the second input …
=> BB-272 - feat(RelationshipEditor): Submit on enter

src/client/components/pages/entities/title.js, src/client/helpers/entity.js
> Currently in BookBrainz, entity aliases do not appear on an entity display page. Take for example the display page for [Lemony Snicket](https://bookbrainz.org/creator/cb5a7089-b36c-463e-9380-331ce94c2873) and compare it to the [edit page](https://bookbrainz.org/creator/cb5a7089-b36c-463e-9380-331ce94c2873/edit) for the same entity, and click on "edit 1 alias". You will see that the entity has 1 alias (Daniel Handler), that is not shown on the display page but visible when editing.
*-from the GCI task page.*
Adds a helper function which returns the aliases.
This is then printed under the title (as `h5` is a block), if there actually are aliases.  
The [title page](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/pages/entities/title.js), and the [entity …
=> Display Entity Aliases

develop.sh, docker-compose.yml
Some users were experiencing issues with ElasticSearch.
The two main issues were:
• ElasticSearch not starting due to low virtual machine memory on the host
• ES was not starting fast enough and the bookbrainz website could not set up correctly
• Added environment variable configuration options in docker-compose file to disable ES bootstrap checks
• Added a container to wait for ES and other dependencies to be up before starting bookbrainz-site
Docker-compose file and develop.sh
=> Docker develop fix

src/client/components/pages/parts/editor-profile.js, src/server/routes/auth.js
The timestamp is same for Joined and Last Active in user's detail.
The database is updated for last login time.
Update label Last Active to Last login same as MusicBrainz.
Client-side: `src/client/components/pages/parts/editor-profile.js`
Server-side: `src/server/routes/auth.js`
=> Update last login time in database to fix issue #BB-311

src/client/components/pages/entities/edition-table.js, src/client/helpers/entity.js, src/server/routes/entity/publication.js, src/server/routes/entity/publisher.js
In the edition group page and publisher page a table of edition was showing.
But in this table only edition name and release date was showing which not sufficient to distinguish between editions.
to solve above problem, add format of edition and isbn with his link by this commit.
Less information in edition to distinguish bw them.
Add isbn and format of an edition in the table.
Now  publisher page:  
Publication page:  
**Client-side**  
`src/client/components/pages/entities/edition-table.js`
`src/client/helpers/entity.js`
**Server-side**  
`src/server/routes/entity/publication.js`
`src/server/routes/entity/publisher.js`
=> feat(edition detail): add format and isbn in edition table to fix #BB-229

src/client/components/pages/entities/identifiers.js, src/client/components/pages/entities/image.js
The warning occurs if propType marked as isRequire and value is null or undefined. 
Remove isRequired from propTypes and set the default props.
=> fix(propType warnings): remove isRequired and set default props to fix propType warnings.

src/client/entity-editor/creator-section/reducer.js, src/client/entity-editor/publisher-section/reducer.js
On the creator page if we add an invalid date then uncheck the died checkbox, the value will be taken from that date. Same for publisher page.
If uncheck the checkbox then the value also reset to empty.
`src/client/entity-editor/creator-section/reducer.js`
`src/client/entity-editor/publisher-section/reducer.js`
=> fix(client-side): reset state if uncheck the checkbox on publisher and creator page.

src/client/components/pages/entities/edition.js, src/client/helpers/entity.js
Edition display page was breaking when loading an edition with deleted edition group or missing sort name 
Protect against missing properties
=> fix(edition): Fix BB-325 Protect against missing edition properties (eg deleted entities)

src/client/entity-editor/name-section/name-section.js, src/server/helpers/entityRouteUtils.js
Since addition of running deduplication on componentDidMount in the name section, deduplication warning appears when editing an existing entity, which is undesirable.
Pass the action type ('create' or 'edit'), and if the action is 'edit', don't run deduplication in componenetDidMount
NameSection component and the props passed to it
=> fix(deduplication): Don't initially run name deduplication on entity edit

src/client/components/pages/entities/edition-table.js, src/client/components/pages/entities/edition.js, src/client/components/pages/entities/links.js, src/client/components/pages/entities/publication.js, src/client/components/pages/entities/publisher.js, src/client/components/pages/entities/work-table.js, src/client/components/pages/entities/work.js, src/client/helpers/entity.js, src/server/helpers/middleware.js, src/server/helpers/utils.js
.
1. Work table contains all the work contained by the edition.
2. Add edition table in the work page, the table contains all the editions who containnig that work.
3. Remove some unused lines of code of import section.
=> feat(workTable): Add work table on the edition page and edition table on the work page. #BB-330

README.md
Fixes [BB-309](https://tickets.metabrainz.org/browse/BB-309)
Added a brief description of the [test subdomain](https://test.bookbrainz.org) of the BookBrainz website to the README file.
=> "fixes BB-309" docs: Add a section about the "test" subdomain in README

README.md
This section was missing a detail on callback URL required to request authorization code when register bookbrainz as developer application with MB.
When registering the developer applicaition, the callback URL needs to match exactly the one specified in config/config.json
README.md
=> doc(revision): update to the configuration section of README.md page

src/server/helpers/middleware.js, src/server/routes/entity/publisher.js
Fixes issue [BB-224](https://tickets.metabrainz.org/browse/BB-244?jql=project%20%3D%20BB%20AND%20issuetype%20in%20(Bug%2C%20Improvement)%20AND%20labels%3Dgood-first-bug)
bluebird warning popping up on stdout when makeLoader middleware function located in src/server/helpers/middleware.js executes between route calls.
Explicitly returned null which was returning undefined on next() yield.
- bookbrainz-site/src/server/helpers/middleware.js
- bookbrainz-site/src/server/routes/entity/publisher.js
=> fix(core): BB-244 Error due to promise not being returned in server/helpers/middleware.js

src/client/entity-editor/common/linked-entity.js, src/client/entity-editor/relationship-editor/relationship-editor.js, src/server/helpers/search.js, src/server/routes/search.js
Some lingering issues with entity names and case after merging PR #271.
Mainly ElasticSearch was broken when searching for multiple types (eg for relationship editor autocomplete) and the clickable link dropdown options from PR #261
=> Fix issues after entity renaming

Dockerfile
Populating database via `database-init-docker.sh` fails because a requirement bzcat is not installed
=> fix(Dockerfile): Add missing bzcat

package-lock.json, package.json
Patching issue with entity table name in bookbrainz-data-js ORM
Updating to version 2.1.1
=> fix: Update bookbrainz-data ORM package version

src/client/components/pages/index.js, src/client/helpers/entity.js, src/server/routes/index.js
• Fix issues with deleted and unnamed entities' display name introduced in PR #280
• Improve code quality of index page recent entities and related SQL query
• Use getEntityLabel utility on index page to ensure displaying of deleted entities is defined only once
=> Refactor deleted entity display

src/server/routes/index.js
I kind of broke the recent revisions on the home page and they show multiple recent revisions for a single entity, instead of only the latest revision per entity.
Forgot a WHERE clause. Woops.
=> fix: fix BB-346 show unique entity in last revisions

src/client/components/pages/index.js, src/client/containers/layout.js, src/client/stylesheets/style.less, src/server/app.js, src/server/routes/index.js
Adds support for disabling the login and register links (one in the top menu bar and one in the middle of the homepage) when a user can't login (Redis session missing).
=> fix: fix BB-341 disable login and register links when redis is down

package-lock.json, package.json
Update Mocha for a sub-dependency security risk (diff package)
=> chore: Fix SEC-16

src/client/entity-editor/common/new-date-field.js, src/client/entity-editor/common/validation-label.js
**Validation text for name (defaultAlias) shows the one for dates**
Issue [BB-354](https://tickets.metabrainz.org/browse/BB-354) 
From **new-date-field**, passed `warnMessage` as a prop to **validation-label** 
Changes in **new-date-field** and **validation-label**
=> add passing warnMessage from new-date-field

src/client/helpers/entity.js
BB-352: Works with malformed identifiers set throw
A check on the existence of entity.identifierSet.identifiers.
src/client/helpers/entity.js
=> fix(display): Works with malformed identifier sets throw error.

src/server/routes/revision.js
The site displays 500 error when visiting a non-existing revision page
Simple condition to check if revision exists or not. If it doesn't exist, 404 error is thrown.
src/server/routes/revision.js
=> BB-339 fix(display): Converted 500 error to 404 error with a meaningful message, when a revision is not found.

src/client/components/pages/parts/call-to-action.js, src/client/components/pages/parts/editor-revisions.js, src/client/components/pages/parts/search-results.js
To show meaningful message when User Revision history is empty.
Add 'Revision History not found' message if revision history is empty.
Also add "call to action".
- src/client/components/pages/parts/call-to-action.js
- src/client/components/pages/parts/editor-revisions.js
- src/client/components/pages/parts/search-results.js
=> fix(display): add 'Revision History not found' message

src/client/components/pages/parts/editor-achievements.js
Rendering Editor Achievements iterates 2 times for splitting into locked & unlocked, which can be optimized
Using single iteration to split achievements into unlocked & locked.
I have kept **Don't prematurely optimize**, **Use ES6/ES7 features** in mind and thought of below codes:
**Using Array.reduce():**
```
reducer(splitAchievements, achievement) {
splitAchievements[achievement.unlocked ? 'achievements' : 'locked'].push(
<Achievement
achievement={achievement}
key={`${this.state.editor.id}${achievement.id}`}
unlocked={achievement.unlocked}
/>
);
return splitAchievements;
}
renderAchievements() {
return this.state.achievement.model.reduce(this.reducer, {achievements: [], locked: []});
}
render() {
const {achievements, locked} = this.renderAchievements();
```
**Using Array.forEach():** …
=> refactor(achievement): refactor renderAchievements

src/server/routes/editor.js
Visiting Editor Achievements page gives 500 error when user is not logged-in (commented [here](https://github.com/bookbrainz/bookbrainz-site/pull/315#issuecomment-550389833))
Check if req.user is undefined, then access req.user.id
**Verified it works now.**
- src/server/routes/editor.js
=> fix(profile,achievement): fix accessing req.user.id when user not logged-in

src/server/helpers/search.js
#BB-310 Search for entity by alias added and was not possible earlier.
Added multi_match query and indexed entity aliases in elastic search.
src/server/helpers/search.js
=> feat(search): The aliases are now searchable.

sql/scripts/SchemaSpy.sh
#BB-359 The SchemaSpy.sh script doesn't work as expected. If an empty string is passed as one of the arguments from the terminal, the script fails with IndexOutOfBoundsException.
All the args variables are surrounded by double quotes to accept empty string args properly
sql/script/SchemaSpy.sh
=> fix(core): Fixed the IndexOutOfBoundsException of SchemaSpy.sh

src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js
Fix issue with language property being reassigned by object destructuring (introduced in PR #308 ).
Also refactor other entities to use the same protection (use languageID instead of language.id in case language is undefined)
=> fix: Reassign alias language id safely

src/server/helpers/search.js
Areas are not indexed since PR #313 
The Area entities returned by the database need to be massaged to fit BB entities' format (using aliasSet.aliases[].name now instead of defaultAlias.name
=> fix(search): Index areas properly

src/client/entity-editor/common/entity-search-field-option.js
#BB-361 Entity search in relationship editor only shows 2 items
Added filterOptions={false} prop to the ImmutableAsyncSelect to disable client side filtering of autosuggested options.
src/client/entity-editor/common/entity-search-field-option.js
=> fix(editor): Client side filtering of autocomplete suggestions disabled in Async.

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, CONTRIBUTING.md, NODEJS_SETUP.md, README.md
Reworked the instructions, and published .vscode files 
Just the markdown repo docs
=> docs: Document local setup and debugging with VSCode

.gitignore, NODEJS_SETUP.md, config/config.local.json.example, src/common/helpers/config.js
[BB-366](https://tickets.metabrainz.org/browse/BB-366) Allow overwriting config file path when running local server 
Added functionality to pass config file path with `--config` flag.
`npm start -- --config ./config/config.local.json`
src/common/helpers/config.js
=> feat(configuration): allow overwriting config file path | BB-366

sql/migrations/2019-05-09/up.sql, src/client/entity-editor/relationship-editor/relationship-editor.js
Like it says on the tin !
A cleanup SQL script is needed to convert those Edition-Edition Group relationships to the Edition Group property of an Edition
=> Hide deprecated relationships in relationship editor

package-lock.json, package.json, src/client/components/pages/index.js, src/client/containers/layout.js, src/client/helpers/entity.js, src/client/helpers/setupIconLibrary.js, src/client/stylesheets/style.less
_react-fontawesome_ doesn't display some icons (brands): [BB-358](https://tickets.metabrainz.org/browse/BB-358)(closed)⏩ [BB-363](https://tickets.metabrainz.org/browse/BB-363)
Migrating _react-fontawesome_ to **official** _react-fontawesome_
Related ticket: https://tickets.metabrainz.org/browse/BB-363
**Client-** Almost all pages which use FontAwesome icons, including Index page, Layout etc
=> migrate react-fontawesome to offical package- BB-358

src/client/entity-editor/common/new-date-field.js
DatePicker disabled by default when date-input-field is empty
isCommonEraDate value checking fix, so that it evaluates to 'true' for both '1' & '0'
Frontend: DatePickers
=> DatePicker fix

src/server/routes/entity/entity.js
Newly created entities did not seem to be indexed by the search server.
Issue was introduced indirectly in PR #313 
Load/refresh the newly saved entity with all aliases rather than just defaultAlias, since we now index entites by all aliases.
src/server/routes/entity/entity.js
=> fix(search): Fixes BB-392: update search server with aliases

src/server/routes/entity/edition.js
https://tickets.metabrainz.org/browse/BB-395
Cannot read property 'year' of undefined
Now it checks if data.editionSection.releaseDate exists or not
=> fix(edition) : Cannot read property 'year' of undefined

scripts/build-client-js.sh, src/client/controllers/error.js, src/server/helpers/error.js
https://tickets.metabrainz.org/browse/BB-396
Dropdown do not work for error page
I added error.js in src/client/controller and made corresponding changing in script/build-client-less-js.sh
=> Fix- #BB-396 : drop down not working for error page

src/client/components/forms/deletion.js, src/server/routes/entity/entity.js
If for some reason there is a communication issue with ElasticSearch (or if it is not running), deleting an entity fails.
The reason is that we use `Promise.all` to resolve the async function `search.deleteEntity` along with the other steps.
Promise.all rejects if any of the promises rejects.
The error messages when submitting on the deletion page itself were appearing at the top of the page, rather than above the submit button
Catch errors on `search.deleteEntity` to prevent Promise.all from rejecting because of a search related issue.
Move the error messages  above the submit button on the front-end page.
- src/server/routes/entity/entity.js
- src/client/components/forms/deletion.js
=> fix(deletion): Delete page improvements

src/client/components/pages/entities/links.js, src/client/components/pages/entities/relationships.js, src/client/entity-editor/common/entity.js, src/client/entity-editor/relationship-editor/relationship.js, src/client/helpers/entity.js, src/client/stylesheets/style.less, src/server/helpers/middleware.js
https://tickets.metabrainz.org/browse/BB-409
Relationships were being rendered by the server into an HTML string and injected directly on the front-end with `dangerouslySetHTML`.
This causes issues if the title of an entity has scripting language in it, opening the door to XSS attacks.
Instead, use the same components we use in the entity editor to render the relationships.
This PR also brings a few small improvements in how relationship are displayed:
• minor visual tweaks
• display disambiguation if it exists (currently it only does so in the entity search fields)
=> BB-409: Fix XSS vulnerability in relationship display

src/client/stylesheets/style.less
https://tickets.metabrainz.org/browse/BB-411
the opacity of  .navabar.BookBrainz has been changed from 0.9 to 1 . 
before>>>
after >>>
only navbar's background opacity is changed
=> changed background opacity of navbar in mobile view

src/client/components/pages/index.js, src/client/components/pages/revisions.js
https://tickets.metabrainz.org/projects/BB/issues/BB-417
For the revisions table, right margin was lesser than left. It was looking unsymmetrical 
In the main page, `see all revisions` button was showing on the left side for smaller screens( mobile)
Removed an unnecessary `<div id=container>` (made it same as search result table)
For the main page, used `pull-right` for `see all revisions` button 
src/client/components/pages/index.js
src/client/components/pages/revisions.js
=> BB-417 fix(revision-table) : remove unneccesary div tag and use 'pull-right'

src/client/components/pages/parts/pager.js, src/client/components/pages/revisions.js, src/client/components/pages/search.js, src/client/stylesheets/style.less
https://tickets.metabrainz.org/browse/BB-406
Refactoring Pagination Component
The bootstrap Pager element is used across various pages (search, revisions page, editor's revisions page), each having a copy of the code.
This PR is about refactoring that pager code into a component that can be reused
Added a new component - PagerElement and reused it for search-results and revision-table
=> Refactor pagination component

docker-compose.yml
https://github.com/docker-library/postgres/issues/681
Due to a recent change in postgres, an empty password was throwing an error.
Modified the environment to allow empty password
docker-compose.yml
=> Docker postgres no password error

src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.js, src/server/routes/entity/entity.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js, test/src/server/routes/entity/entity.js
The defaultAlias was not necessarily the one appearing in the main nameSection on the entity editor page, while showing correctly both on the display page and API requests
The problem hence must come from how we transform a DB entry (or its ORM representation) into the entity-editor page state.
Sure enough, it was just trying to get the first alias in the aliasSet that has 'default' set to true, which turned out to be a problem when merging: I ended up with multiple aliases with default set to true (one for each entity merged) but only one corresponding to the aliasSet's defaultAliasId.
I reworked the utility to be more resilient and also wrote a few tests for it while I was there.
It also turned out most entities used an identical copy of the utility each in its page, instead of all …
=> Default alias selection

src/client/entity-editor/alias-editor/alias-editor.js, src/client/entity-editor/alias-editor/alias-row.js, src/client/entity-editor/identifier-editor/identifier-editor.js, src/client/entity-editor/identifier-editor/identifier-row.js, src/client/entity-editor/relationship-editor/relationship-editor.js, src/client/entity-editor/relationship-editor/relationship-section.js, src/client/helpers/setupIconLibrary.js
Relationship Section was like this before
Icons for `edit`, `remove` and `add relationship` were missing
Added corresponding icons
src/client/entity-editor/relationship-editor/relationship-section.js
=> Add icons in entity editor buttons

src/server/helpers/utils.js
Revisions page shows only one affected entity per type
Because there were multiple rows with same 'id' in EntityRevision table (work_revision, author_revision, etc) , `merge: false` and `remove: false` had to be used to multiple rows.
src/server/helpers/utils.js
=> Multiple entities not visible in revision table

src/client/components/pages/parts/search-results.js
https://tickets.metabrainz.org/projects/BB/issues/BB-431
On the search page, links to results are currently opening in a new tab which is a bit frustrating, breaking tab history when you only go to a single search result.
In most (all?) browsers, there’s no way to reasonably circumvent this, while Ctrl+click is a common(/universal?) way to make links open in new tabs when you do want that behaviour.
src/client/components/pages/parts/search-results.js
=> Don’t open search results in new tab

config/config.json.example, config/config.local.json.example
Elasticsearch does not work as the older version is getiing installed 
Changes the elasticsearch api version to .56
Changes 2 config files
=> Elasticsearch APIversion fix to 5.6

src/client/components/pages/revision.js, src/client/stylesheets/style.less
…in revision notes
https://tickets.metabrainz.org/projects/BB/issues/BB-436
revision note does not respect newlines
used `white-space: pre-wrap` to handle white spaces 
src/client/components/pages/revision.js
=> BB-436: Revision Note Newlines fix

src/client/components/pages/editor-revision.js, src/client/components/pages/parts/pager.js, src/client/components/pages/revisions.js, src/client/components/pages/search.js, src/client/controllers/search.js, src/server/helpers/utils.js, src/server/routes/editor.js, src/server/routes/revisions.js, src/server/routes/search.js, test/src/server/helpers/utils.js
https://tickets.metabrainz.org/browse/BB-419
`Next` button in pager was wrongfully enabled in some special cases. 
https://beta.bookbrainz.org/editor/56/revisions?size=11
https://bookbrainz.org/search?q=harry+potter&size=1
Also when you visit this link, `nextEnabled` is disabled, it should be enabled. This PR solves this bug as well 
This was because of `nextEnabled: data.length>=size`
For all the pages which use pagination - ./search, ./revisions, ./editor/id/revisions -  I checked `nextEnabled` by getting 1 more entity than `size`
Did the same for `triggerSearch` function as well.
=> Pager next enabled 

test/test-helpers/create-entities.js
Errors are thrown in various places in create-entities test helpers when trying to create multiple test entities because of duplicate IDs.
Instead of a static id, create a random ID every time where needed.
Also cleaned up unused function;
test/test-helpers/create-entities.js
=> BB-435 (test): Allow creation of multiple test entities

src/server/routes/editor.js, src/server/routes/revision.js
https://tickets.metabrainz.org/projects/BB/issues/BB-443
Revision Notes were not sorted.
Sorted the notes while fetching them. </br>
src/server/routes/editor.js
src/server/routes/revision.js
=> BB-443: Revision Notes Ordering

src/client/components/pages/parts/editor-achievements.js
noticed a little discontinuity under the achievement tab in the profile page. The background behind the update button is little discontinuous which causes a trouble for eyes while scrolling. Just changed some margins to make the content a little more clear.
fixing ticket: BB-447
=> fix(achievement): UI improvement in achievement tab

src/client/stylesheets/style.less
FontAwesome icons were not aligned properly
Added `vertical-align: -.125em` for icons
=> BB-418: FontAwesomeIcon Alignment  

src/server/app.js, src/server/helpers/middleware.js, test/src/server/routes/entity/author.js, test/src/server/routes/entity/edition-group.js, test/src/server/routes/entity/edition.js, test/src/server/routes/entity/publisher.js, test/src/server/routes/entity/work.js, test/test-helpers/create-entities.js
Following PR #402 , the create route for entities (i.e: `/work/create`) throws an "Invalid BBID" error
Modify the entity loading middleware to accept the `/create` route path, since we have no good way to differentiate a mistyped BBID and a valid route. 
Also added basic tests for the entity routes to make sure we don't break them as easily in the future.
=> Fix entity /create route

src/client/containers/layout.js, src/client/helpers/setupIconLibrary.js
The revisions page is quite an important new page, and it should be accessible on every page.
Add new menu item to navbar
=> feature(navbar): Added menu item pointing to revisions page

src/server/routes/entity/entity.js
An elusive search indexing issue was introduced in PR #313.
Tried to solve it a couple of times already with PRs #330 and  #362 which both failed to address the issue.
It also shone a light on a problem with my local debugging setup swallowing console errors.
Refresh entities after save; contrarily to what I thought, the ORM does not return a completely refreshed entity after a `.save` operation as described [in the BookshelfJS docs](https://bookshelfjs.org/api.html#Model-instance-save):
> After a model is saved it will be populated with all the attributes that are present in the database, so you don't need to manually call refresh to update it. This will use two queries unless the database supports the RETURNING statement, in which case the model will be saved and its data fetched with a …
=> BB-367 fix(search): Fix entity search indexing

package-lock.json, package.json
Upgrading the flow version from the 0.69.0 to the latest, 0.123.0
I first removed the current flow version with `sudo rm -rf path` then `yarn global add flow-bin@latest` then after that `npm install flow-bin@latest`.
package.json
package-lock.json
I haven't changed the source codebase because on doing `yarn create flow-upgrade --all` it did following changes in around 103 files disturbing the eslint-sort:
`import React from 'react';` changed to `import * as React from 'react';`
`class Achievement extends React.Component {` to  `class Achievement extends React.Component<$FlowFixMeProps, $FlowFixMeState> {`
=> BB-455: Update Flow Version

src/client/components/entity-link.js, src/client/components/pages/revision.js, src/client/stylesheets/style.less, src/server/helpers/diffFormatters/entity.js, src/server/routes/revision.js
WIP
PR not ready for review rn
=> BB-444: Revision Display Page Improvement (WIP)

src/client/entity-editor/edition-section/edition-section.js, src/client/entity-editor/name-section/name-section.js
After PR #383 , mentions of "click to open in a new tab" are wrong and misleading and will lead to users losing their progress and patience.
Replaced it with text suggesting shortcut to open in a new tab.
=> fix: fix mentions of "open in a new tab"

src/server/helpers/middleware.js, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js
Links to merged bbids subpaths (for example `/$BBID/revisions`) would redirect to the merged entity without the subpath  (i.e: `/$newBBID`).
Replace the bbid in the full path and redirect to that.
This PR also puts entity routes without BBIDs (/create, /create/handler) before the route parameters are defined for routes with bbids.
This allows us to remove an ugly solution to detect routes without bbid introduced in this commit:
https://github.com/bookbrainz/bookbrainz-site/commit/0e1a8349f6cdc9bc6d97f6416eb5c0a0049f2c08#diff-04b1046083d3d54b6df49ebe87477558
Also adds a bit of flow types
Entity router files and middleware helpers.
=> BB-481: Fix merged entities path redirect

src/server/helpers/revisions.js, src/server/routes/entity/entity.js, test/src/server/helpers/revisions.js
Once entities are merged, their revision history is hidden and unaccessible
This PR loads the revisions for entities that  have been merged, thus presenting the full revision history tree.
=> feat(merge-tool): Show full revision history of merged entities

src/server/helpers/revisions.js, test/src/server/helpers/revisions.js
Fixes shortcomings of PR #430.
The issue was that previously merged entities do not point to newly merged entity BBID.
For example, if entity A was merged into entity B, BBID A will point to BBID B.
Now if entity B is merged in entity C, BBID B will point to BBID C.
To allow for reverting merges cleanly, BBID A still points to B and not C (this allows us to revet the merge of B -> C while keeping the merge A-> B).
In order to fetch the complete history tree containing all three entities, we need to recursively check if a source_bbid appears as a target_bbid in other rows.
=> feat(merge-tool): Get full history of merged entities

src/client/components/pages/parts/merge-queue.js, src/client/helpers/setupIconLibrary.js, src/server/routes/merge.js
Currently, only way to select which entity to merge into is to select it for merge first.
That's just bad UX.
Adds a button in the merge queue component to select which entity to merge into, and corresponding endpoint.
=> feat(merge-tool): Allow user to select merge target

sql/migrations/2020-04-29/down.sql, sql/migrations/2020-04-29/up.sql
Identifier IMDb title ID was currently being used for Edition, which should be changed to Work entities.
I have changed the entity_type in identifier_type to 'Work'. Also removed the identifiers from the identifier_set of the Edition and added it to the identifier_set of the relevant Work.
Database
=> BB-463: Identifier "IMDb title ID" fix

src/client/components/entity-link.js, src/client/components/pages/parts/merge-queue.js, src/client/entity-editor/entity-merge.js, src/server/routes/merge.js
Instead of having buttons on each row in the merge queue, add a redio button to select items, then add overall buttons to delete selected entity or to merge all into selected entity.
Also adds BBID in merge queue for easier differentiation.
=> feat(merge-tool): Modify "merge into X" functionnality

src/client/entity-editor/submission-section/actions.js, src/client/entity-editor/submission-section/reducer.js, src/client/entity-editor/submission-section/submission-section.js
A user can mash the submit button and the form will be submitted as many times as they clicked it before being redirected.
That's obviously an issue and resulted in a bunch of duplicates in the database.
Disable the submit button once submitted.
re-enable it if there was an error with the submission.
While I was in there, I also fixed a small issue introduced in #438 where a submission error message was not extracted properly from the response body following the replacement of superagent-bluebird-promise  library with superagent itself.
=> Fix BB-453: Prevent multiple form submissions

src/client/components/forms/userCollection.js, src/client/controllers/collection/userCollectionForm.js, src/client/entity-editor/common/entity-search-field-option.js, src/server/helpers/auth.js, src/server/helpers/collectionRouteUtils.js, src/server/helpers/middleware.js, src/server/helpers/search.js, src/server/routes.js, src/server/routes/collection.js, src/server/routes/search.js, webpack.client.js
Added Collection-Create/Edit Route
=> User collections create/edit route

src/client/components/pages/entities/annotation.js, src/client/components/pages/entities/author.js, src/client/components/pages/entities/edition-group.js, src/client/components/pages/entities/edition.js, src/client/components/pages/entities/publisher.js, src/client/components/pages/entities/work.js, src/client/entity-editor/submission-section/actions.js, src/client/entity-editor/submission-section/reducer.js, src/client/entity-editor/submission-section/submission-section.js, src/client/entity-editor/validators/common.js, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.js, src/server/routes/entity/publisher.js, src/server/routes/entity/work.js
https://tickets.metabrainz.org/browse/BB-415
Annotations were being deleted automatically on editing an entity, and there was no way to display or edit the annotations.
Reimplement annotations on the server and allow to edit and display them on the client.
Un-delete the annotations https://tickets.metabrainz.org/browse/BB-493
=> Fix BB-415: Reimplement annotations

package-lock.json, package.json, src/client/entity-editor/alias-editor/alias-editor.js, src/client/entity-editor/identifier-editor/identifier-editor.js, src/client/input.js, src/client/stylesheets/style.less
Replaces the react-tooltip library with the tooltips from react-bootstrap.
We use react-bootstrap in a lot of places, so it's unlikely to go away anytime soon.
Also removes explicit dependency on react-virtualized (still a dependency of react-virtualized-select library that we use for language selects)
=> chore: Remove react-tooltip package

.travis.yml, src/api/app.js, src/api/helpers/formatEntityData.js, src/api/routes.js, src/api/routes/search.js, src/common/helpers/search.js, src/common/helpers/utils.js, src/server/app.js, src/server/helpers/middleware.js, src/server/helpers/search.js, src/server/helpers/utils.js, src/server/routes/entity/entity.js, src/server/routes/merge.js, src/server/routes/search.js, src/server/routes/statistics.js, test/src/api/common-tests.js, test/src/api/helpers.js, test/src/api/routes/test-search.js, test/test-helpers/create-entities.js
=> feat(search): add search endpoint for API

src/api/helpers/entityLoader.js, src/api/routes.js, src/api/routes/author.js, src/api/routes/edition-group.js, src/api/routes/edition.js, src/api/routes/publisher.js, src/api/routes/work.js, src/common/helpers/search.js
- Missing defaultAlias language in search results (for API endpoint iso code)
- Missing swagger definitions and misc. corrections
- Log errors in makeEntityLoader
=> docs(api): Clean up API & swagger definitions

src/server/routes/search.js
https://test.bookbrainz.org/search?q=harry+potter&from=20
In the pagination, this should be showing `21-40` but is showing `1-20`
`from` was not passed in the props
=> Fix: Pagination is showing wrong range in some cases

package-lock.json, package.json, src/api/helpers/rateLimiter.js, src/api/routes.js
Add rate limiting to the API routes.
Slows down the response after X requests in a specifid time window.
Initial settings are: 
- browse and lookup endpoints: 100 requests /  5 minutes, then += 500ms* requests after that
- search endpoint: 100 requests /  5 minutes, then += 500ms* requests after that
Request # 101 is delayed by 500ms, # 102 is delayed by 1000ms, etc.
This will prevent over server from DOS attacks and control the request traffic
Slow Down configurations are only, for example, We can update those after a discussion on IRC.
Sever may slow or down on high request traffic.
Implemented request slow down with configuration.  To implement this [express-slow-down](https://www.npmjs.com/package/express-slow-down) is used.
Server-side
=> feat(API): add basic rate limiter

src/client/components/forms/userCollection.js, src/server/helpers/collectionRouteUtils.js, src/server/routes/collection.js
Collection Type field was editable for non empty collections
=> fix: disable edit EntityType field for non empty collection

src/client/components/pages/editor-revision.js, src/client/components/pages/entity-revisions.js, src/client/components/pages/parts/pager.js, src/client/components/pages/parts/search-field.js, src/client/components/pages/revisions.js, src/client/components/pages/search.js, src/server/routes/search.js
**I couldn't reopen #470 for some reason, so I'm opening this new PR instead.**
https://tickets.metabrainz.org/browse/BB-471
Pagination parameters (search query, size, page) aren't reflected in the browser's address bar or history.
Previous/Next buttons in pagination component now save the parameters in the browser's history (thus updating the address bar and allowing for browser button navigation).
Upon browser navigation, we also needed a way to send back other query parameters back to the parent component (in the case of search page [i.e. `?q=myquerry&type=author`]).
This required a small refactor to handle a search parameters string instead of just the query string
Pager component 
Search page component
Small touch (remove '?' from pagination url) on other pages that use pagination.
=> BB-471: Save pagination parameters in url bar 

test/src/server/routes/collection.js
Tests for POST `collection/:collectionID/delete/handler`
=> Test: Delete Collection

src/client/components/pages/parts/search-results.js
If you select `Editor` or `Area` or `Collection` in the search results, you can press `Add to collection` button and it doesn't throw any error.
=> fix: throw error when trying to add collection, area, editor to a collection

.travis.yml, src/server/routes/collection.js, test/src/server/routes/collection.js
After deleting the collection from Database, it has to be deleted from ES index as well
=> Delete collection from Elasticsearch index

src/client/stylesheets/style.less
With the User Collections we're doing new things with buttons that we haven't done before, which is unearthing a couple of small CSS issues.
For some reason the Lobes theme has slightly overlapping buttons, which means an opacity change (disabled) looks really bad.
We're also using badges in buttons which requires a small padding adjustment.
Buttons are overlapping, which looks terrible with opacity (disabled buttons).
Also buttons with badges are a tiny bit higher that without.
Adjust button css here and there:
Just the LESS file.
=> fix(css): Adjust button margins

test/src/api/routes/test-author.js, test/src/api/routes/test-edition-group.js, test/src/api/routes/test-edition.js, test/src/api/routes/test-publisher.js, test/src/api/routes/test-work.js, test/src/server/helpers/revisions.js, test/src/server/routes/editor.js, test/src/server/routes/entity/entity.js, test/test-helpers/create-entities.js
Tests were failing erratically because of two reasons:
1. We were assigning an id to pretty much all the test fixtures we created using the ORM, when it's not necessary
2. The random number generator we were using to generate the ids was creating conflicting ids
Let the database create ids, which required a few changes in the test helpers.
Tests only.
=> test: Prevent conflict in test fixtures ids

test/src/server/routes/collection.js
One test was inconsistent and showing false negative. Adding timeout after deleting a collection will make sure that ES index is updated
wait 500ms after deleting a collection to make sure ES index is updated
test/src/server/routes/collection.js
=> fix(test): add 500ms timeout after deleting a collection

src/client/components/pages/collection.js, src/client/components/pages/collections.js
Pagination is collection table was not working properly
fixed the pagination url. Removed an extra `?`
=> fix pagination url for collection table

src/client/components/forms/userCollection.js
changing default privacy of a collection to public
=> Collection: Change default privacy to public

src/server/helpers/middleware.js, test/src/server/routes/collection.js
An error was occurring while creating Edition-Group collection.
In the `paramValidation` middleware, I forgot to take convert entityType to `camel-case` before validating it.
src/server/helpers/middleware.js
test/src/server/routes/collection.js
=> fix: convert collectionType to appropiate format before param-validation

src/server/routes/merge.js
In merge page, annotations are concatenated with a separator ('———').
If the first entity doesn't have an annotation, a separator will still be added before the annotation of the following one.
Instead, only add separator if the string is not empty.
Follows PR #508 .
=> fix(merge-annotations): Don't show separator if no previous text

src/client/entity-editor/relationship-editor/relationship-editor.js, src/client/entity-editor/relationship-editor/relationship-section.js, src/client/entity-editor/relationship-editor/relationship.js, src/client/entity-editor/relationship-editor/types.js
Deployed on test.bookbrainz.org for testing.
This PR adds a few new features to improve the relationship editor:
1. hierarchy in relationships in the relationship editor:
2. help tooltips when hovering over a relationship, both in the rel editor and the entity pages:
3. Help text under the relationship select, once a relationship has been selected
4. Disambiguation is shown in relationship select (for entities with the same name)
5. An "open in a new tab" button next to the entity select in the relationship editor
=> Hierarchy and help text for relationships

src/server/routes/entity/entity.js
Edition Groups created automatically by the ORM ([when no EG is set on a  new Edition](https://github.com/bookbrainz/bookbrainz-data-js/blob/master/src/util.js#L249-L262)) were not being indexed for search.
=> fix(BB-452): Index auto-created Edition Groups

README.md, src/api/swagger.js
See https://tickets.metabrainz.org/browse/ORG-45 following summit discussions.
=> fix(ORG-45): Add blog link to readme and API docs

src/server/routes/entity/entity.js
Bug introduced in commit e7cbb20f01f5ee4032bee1eba8ca58ec95054d66, which does not allow setting relationshipSetId to `null` (for entities where all relationships have been deleted)
Allow setting relationshipSetId to `null`
=> fix(BB-545): Allow relationship sets to be null (empty)

src/server/helpers/middleware.js, src/server/routes/merge.js
When loading relationships, follow the redirected BBID of potential merges to fetch with alias
=> fix(relationships): Follow BBID redirects when loading relationships aliases

package-lock.json, package.json, src/client/entity-editor/common/linked-entity.js, src/client/entity-editor/edition-section/actions.js, src/client/entity-editor/edition-section/edition-section.js, src/client/entity-editor/edition-section/reducer.js, src/client/entity-editor/name-section/actions.js, src/client/entity-editor/name-section/name-section.js, src/client/entity-editor/validators/edition.js, src/client/helpers/setupIconLibrary.js, src/server/routes/entity/edition.js
This PR addresses a few issues with name deduplication and other search-related mechanisms in the entity editor:
- [BB-356](https://tickets.metabrainz.org/browse/BB-356): Editions with the same name should be allowed
- [BB-413](https://tickets.metabrainz.org/browse/BB-413): Name deduplication triggers for the entity being edited
- [BB-537](https://tickets.metabrainz.org/browse/BB-537): Don't auto-select matching Edition Group
1) Allow Editions and Edition Groups with the same name (without requiring a disambiguation)
2) Autocomplete and deduplication mechanisms should filter out the entity being edited from its results to avoid conflict with itself.
3) For an Edition with a name matching that of an Edition Group, instead of auto-selecting the first exact match, display a list of exact …
=> Name deduplication improvements

src/client/helpers/entity.js, src/common/helpers/error.js, src/server/routes/entity/entity.js
https://tickets.metabrainz.org/browse/BB-554
A couple of compounded issues:
1. Part of the merge operation fails when merging a Publisher without editions
2. That error is swallowed, and the operation finishes successfully instead of throwing error to user
3. Error message was not shown to end users, just a generic message
4. Front-end: Edition display page was throwing error if publisher had no defaultalias
1. Don't call Edition model methods if there is no edition at all (duh.)
2. Throw error down the await/async chain
3. Create SiteError with the actual error message
4. Safely read defaultAlias.name and otherwise show bbid instead
=> BB-554: Issues when merging Publishers without Editions

src/server/helpers/handler.js, src/server/routes/editor.js
The code for handling editor route requests currently uses long chains of promises, which can be hard to follow and reason about. The current use of promises also enforces unnecessary serialization of some database operations. Code is duplicated in several places, and some minor bugs are present.
This PR mainly re-writes the code using promise chains to use ES6 async/await to express asynchronous code in a flat, linear format. It also refactors some code to pull out commonly used data-fetching snippets into separate functions, which could be migrated to the bookbrainz-data-js package in future. Some other minor code quality improvements are also implemented.
Impacts two files:
* `src/server/routes/editor.js`
* `src/server/helpers/handler.js`
The change to handler.js impacts how responses …
=> Editor server cleanup

src/client/entity-editor/name-section/actions.js
The introduction of Typescript in PR #531 has unearthed an unexpected use of the `log` package (server-side logging utility) in the client code, which we do not want.
This was the only use of in in the client code, in the entity editor's name section redux actions.
=> fix(entity-editor): Remove use of log package in client code

src/client/components/pages/parts/editor-profile.js
Following some recent forum drama, it has become more pressing to have a messaging system available on the website.
This PR aims to be a stopgap using the existing MusicBrainz infrastructure until a messaging system is developed for BookBrainz.
This new link redirects to the MusicBrainz email contact page/form (in a new tab).
=> feat(editor): Add "send email" link to user profile

src/client/components/forms/deletion.js, src/server/routes/entity/entity.js
[BB-560:](https://tickets.metabrainz.org/browse/BB-560) Make revision note mandatory when deleting an entity
[BB-566:](https://tickets.metabrainz.org/browse/BB-566) Revision notes aren't being saved when deleting an entity
Send note content (duh!) when submitting deletion, add some simple form validation and feedback to make the note compulsory, and add a bit of text to invite unsure user to contact the forums or IRC channel
=> Deletion form note improvements

src/client/components/forms/userCollection.js, src/client/stylesheets/style.less
https://tickets.metabrainz.org/browse/BB-558
Applied top margin for mobile screens using media query.
src/client/components/forms/userCollection.js
=> Fixed responsiveness of buttons in create-collection page

src/client/components/forms/profile.js, src/client/components/input/select-wrapper.js, src/client/input.tsx, src/common/helpers/search.js, src/server/helpers/handler.js, src/server/routes/editor.js
https://tickets.metabrainz.org/browse/BB-544
Errors thrown are being completely swallowed by the editor profile edit form on the server and front-end, leaving the user with a spinning loader and nothing else.
First, since we're here, a bit of cleanup and renovating, moving to using await/async and fetch and such.
Second, on the server, do some validation and return better error messages.
Finally show said error messages to the user in the profile form.
=> BB-544: Improve Editor form and error handling

src/client/entity-editor/relationship-editor/relationship-editor.tsx, src/client/entity-editor/relationship-editor/relationship-section.tsx
In the relationship section and relationship editor (in entity editor), show the new entity's current name instead of "New Entity":
- src/client/entity-editor/relationship-editor/relationship-editor.js
- src/client/entity-editor/relationship-editor/relationship-section.js
=> feat(relationships): Show new entity name in relationship editor

src/client/components/pages/entities/work-table.js, src/client/entity-editor/name-section/name-section.js
Fixed the url discrepancy in entities (earlier it used to appear as 'W+ork' instead of 'work' in url).
Also there was a possible discrepancy in name-section url where kebab-casing was missing 
A pretty straight-forward fix for the first case and a lodash kebabCasing in the second case
=> fix(display): url discrepancy in entities and entity-editor name-section

sql/migrations/2021-author-credits/down.sql, sql/migrations/2021-author-credits/up.sql, sql/scripts/create_triggers.sql
As it says on the tin, this PR adds an `author_credit_id` column to the database schema definition and trigger for Edition Groups, allowing us to link an Author Credit to an Edition Group as we do for Editions.
=> feat(AC): Add author_credit_id column to Edition Group schema

src/client/components/forms/userCollection.js
Position of "Add another collaborator" button is not intutive.
Instead of displaying the button at the bottom, I have moved it next to the Collaborator's heading as suggested.
=> fix(collection-form):Position of "Add another collaborator" button

src/client/stylesheets/style.less
https://tickets.metabrainz.org/projects/BB/issues/BB-582?filter=allopenissues
Add a scrollbar to prevent the content from overflowing and to give a better user experience. 
Here are the Screenshots,
Before,
After,
=> Add a scrollbar in the 'add to collection' modal

src/client/stylesheets/style.less
This PR Fixes: [BB-565](https://tickets.metabrainz.org/browse/BB-565)
**Removed the css rule that was adding the quotes**
**Stylesheet**
=> FIX(BB-565): Removed extraneous quotation marks from revision notes

NODEJS_SETUP.md
The link associated with the keyword `are running them manually` seems to be broken and resulting in 404 error page
Updated [NODEJS_SETUP.md](https://github.com/bookbrainz/bookbrainz-site/blob/master/NODEJS_SETUP.md) with the correct link.
[NODEJS_SETUP.md](https://github.com/bookbrainz/bookbrainz-site/blob/master/NODEJS_SETUP.md)
=> [DOCS] Fixed invalid link in NODEJS_SETUP.md

src/client/components/pages/collection.js
This PR Fixes [BB-591](https://tickets.metabrainz.org/projects/BB/issues/BB-591?filter=allopenissues)
added margin to buttons
[Collection page](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/pages/collection.js)
=> FIX(BB-591): Added margin to buttons on collections page 

src/client/components/pages/parts/collections-table.js, src/client/stylesheets/style.less
Thir PR Fixes: [BB-587](https://tickets.metabrainz.org/projects/BB/issues/BB-587?filter=allopenissues)
**Added a media query for smaller viewports**
=> FIX(BB-587): Better button alignment for smaller viewports

src/client/helpers/entity.tsx, src/client/stylesheets/style.less
Some Older version of CSS does not support certaion CSS properties
By adding vendor pefix we can tackle this
CSS Styles
=> FIX (BB-456) : CSS style issue in older version of certain browsers

src/client/helpers/entity.tsx
Remove trailing space so that selections will not contain a space at the end
Currently `getLabelEntity` adds a space at the end. Looks like Label is always followed by disambiguation and `getEntityDisambiguation` already [prefixes a space](https://github.com/bookbrainz/bookbrainz-site/blob/c908c2135aaed62c7448977a74ece5c6fd462524/src/client/helpers/entity.tsx#L217). So this should not be a problem :)
Text selection in title will be easier
=> fix: Removed trailing space in getEntityLabel (BB-601)

src/client/entity-editor/common/new-date-field.js
Closes BB-604
fixes date picker popper position in author section
Changed the position by setting popperPlacement prop
src/client/entity-editor/common/new-date-field.js
=> fixes date picker popper position in author section on smaller viewports

src/client/stylesheets/style.less
**This PR Fixes: [BB-527](https://tickets.metabrainz.org/browse/BB-527)**
Applied some **CSS** rules to react-select `<Select />` Component
**Now we can paste values into the input field with mouse click**
https://user-images.githubusercontent.com/55311336/113511977-23912780-9580-11eb-87e1-0241261b51bd.mp4
This issue can be fixed without upgrading to react-select v2
In the ticket it is mentioned that
> This will probably require updating to react-select v2 (https://react-select.com/upgrade-guide)
If we wish to upgrade to react-select v > 1. Then we need to tackle some changes in our  **style.less** file. Since react-select v1 uses **LESS / SCSS** stylesheets but version > 1 removed LESS / SCSS for styling and adapted emotion.
So first we will need to remove the following from style.less …
=> FIX(BB-527): Paste values into react-select input using mouse

src/client/components/pages/parts/collections-table.js, src/server/routes/collections.js
Closes BB-596
Added My collections button
Public collections page
Viewing other collections
Clicking on my collections
=> added my collections button

src/common/helpers/search.js
Closes BB-577
Search autocomplete endpoint responses are limited to 10 results
Changed the search autocomplete endpoint limit by including  size property in dslQuery object body
src/common/helpers/search.js
=> Autocomplete search limit

src/client/components/pages/parts/merge-queue.js, src/client/stylesheets/style.less
**This PR Fixes: [BB-606](https://tickets.metabrainz.org/projects/BB/issues/BB-606?filter=allissues)**
**Added some margins to buttons** 
[merge-queue.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/pages/parts/merge-queue.js)
=> FIX(BB-606): Buttons overlapping in merge entity section

src/client/components/pages/entities/annotation.js, src/client/stylesheets/style.less
**This PR Fixes: [BB-615](https://tickets.metabrainz.org/projects/BB/issues/BB-615?filter=allissues)**
**Replaced the current `<p class="annotation-content">` with a `<pre class="annotation-content">` and overridden the existing `<pre>` css styles when className `annotation-content` is present.**
**Also Tested in some older version of Firefox browsers using BrowserStack.** 
[annotation.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/pages/entities/annotation.js)
[style.less](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/stylesheets/style.less)
=> FIX(BB-615): Copy/Paste annotation text  in FireFox <= 60

src/client/components/pages/revision.js, src/client/stylesheets/style.less, src/server/helpers/diffFormatters/entity.js, src/server/routes/revision.js
**This PR Fixes: [BB-523](https://tickets.metabrainz.org/projects/BB/issues/BB-523?filter=allopenissues)**
Refactored the `isNew` property logic in **server/routes/revision.js** by taking advantage of `dataId`( which is **null** for a deleted entity)
server/routes/revision.js
=> FIX(Revision): "New" badge appears in entity deletion revision

package-lock.json, package.json, src/client/components/pages/parts/collections-table.js, src/client/input.tsx, src/server/helpers/collections.js, test/src/server/helpers/collections.js
https://tickets.metabrainz.org/browse/BB-580
Adding a column which displays No. of entities in a collection 
I have created a helper function getCollectionSize() which returns the count of UserCollectionItems in each collection. I then used this function to add a property named 'noOfEntities' to each item in the collectionsJSON array which was returned from getOrderedPublicCollections()
Now the function getOrderedPublicCollections() will return an additional property with each collection object : noOfEntities
=> feat(Collections): added a 'No.of Entities' column to Collections table

.travis.yml, package.json
Node.js 10.x is end-of-life on 2021-04-30.
Bump the minimum supported version to Node 12, which is now the oldest LTS release.
None.
=> chore: drop support for node 10, which is EOL today

src/client/components/pages/parts/search-field.tsx, src/client/entity-editor/author-section/author-section-merge.tsx, src/client/entity-editor/author-section/author-section.tsx, src/client/entity-editor/button-bar/button-bar.js, src/client/entity-editor/edition-group-section/edition-group-section-merge.tsx, src/client/entity-editor/edition-group-section/edition-group-section.tsx, src/client/entity-editor/edition-section/edition-section-merge.tsx, src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/entity-editor.tsx, src/client/entity-editor/name-section/name-section-merge.js, src/client/entity-editor/name-section/name-section.js, src/client/entity-editor/publisher-section/publisher-section-merge.tsx, src/client/entity-editor/publisher-section/publisher-section.tsx, src/client/entity-editor/relationship-editor/relationship-editor.tsx, src/client/entity-editor/submission-section/submission-section.js, src/client/entity-editor/work-section/work-section-merge.tsx, src/client/entity-editor/work-section/work-section.tsx
As reported in [BB-543](https://tickets.metabrainz.org/browse/BB-543), pressing enter in a field in the entity editor page does not submit the page as a user should expect.
We were not using a properly formatted form in the entity editor, which was breaking default browser functionality.
One issue was the lack of a parent `<form>` element with an `onSubmit` property, and making our submit button of `type="submit"`.
The other issue was multiple nested form elements, which is not supported like that in HTML.
This PR fixes the form structure and re-enables default browser behavior.
=> BB-543: Enable native html form functionality

src/server/helpers/achievement.js
This PR Fixes: [BB-598](https://tickets.metabrainz.org/projects/BB/issues/BB-598?filter=allissues)
A lot of the code uses promises in the `promise.then(…)` format, which makes the code hard to read and maintain. Rewritten it using the **async/await** syntax
file [src/server/helpers/achievement.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/server/helpers/achievement.js)
=> Refactor(achievement): Rewritten Achievements helpers with async/await syntax

Dockerfile
Node 10 is end-of-life, so it's time to upgrade !
Chose to upgrade to Node 16 which will be LTS later this year.
Had to upgrade postgres-client version (jessie distribution not available anymore, see https://github.com/metabrainz/listenbrainz-server/commit/e9d4b804e72705b8527ec8d1603de7af28bb67ab) and install libpq5 package.
There has also been a change in how NPM runs as root in Docker, which required a couple of adjustments and making sure we run various commands as the right user
=> Update Docker prod image to use Node v16

src/client/components/pages/parts/collections-table.js
A bug was introduced in PR #592 when the template string `/editor/${user.id}/collections` would throw an error if no user is logged in ("Cannot read property 'id' of null")
Refactored these buttons to only be defined if the relevant conditions apply, rather than having a separate boolean to determine if they should be shown (while creating the button every time nonetheless)
=> fix: Collections page bug when no logged in user

src/client/components/pages/parts/editor-profile.js
The **alignment** of achievement title is not **center** aligned because of a small typo in the code.
Fixed the incorrent classname `text=center`
- [editor-profile.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/components/pages/parts/editor-profile.js)
=> FIX:  Alignment of Achievement Title

src/common/helpers/search.js
Allow searching by enitity identifiers
This PR Fixes: [BB-616](https://tickets.metabrainz.org/projects/BB/issues/BB-616?filter=allissues)
Added identifiers to elasticSearch index and match query.
Searching **H. P. Lovecraft** using it's VIAF identifier ID **66470391**
- [helpers/search.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/common/helpers/search.js)
=> feat(elasticSearch): search entities by identifiers

src/server/helpers/diffFormatters/entity.js
Part of the issue [BB-592] is that the path length comparison used to determine if an alias language has changed excluded language name changes.
I believe this partly replaces #603, although I am seeing another issue: when doing the diff between revisions, sometimes the alias language properties are attached to the revision and some other times not, which breaks the diff.
In particular this PR does not solve the issue of the link in the description of BB-592.
Before:
After:
=> [BB-592]-1: Fix alias language diff formatter

src/server/helpers/diffFormatters/base.js, src/server/routes/revision.js
Revisions for **workType, authorType, publisherType, editionGroupType, editionFormat and editionStatus** are not shown in the revision page.
- Fixed some incorrect path name.
- Modified formatChange function and conditional statement.
<details>
<summary>1</summary>
</details>
<details>
<summary>2</summary>
</details>
- [diffFormatters/base.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/server/helpers/diffFormatters/base.js)
- [routes/revision.js](https://github.com/bookbrainz/bookbrainz-site/blob/master/src/server/routes/revision.js)
=> fix(revision): show type changes in revision page

src/client/entity-editor/relationship-editor/actions.ts, src/client/entity-editor/relationship-editor/reducer.js, src/client/entity-editor/relationship-editor/relationship-editor.tsx, src/client/entity-editor/relationship-editor/relationship-section.tsx, src/client/entity-editor/relationship-editor/relationship.tsx, src/client/entity-editor/relationship-editor/types.ts, src/client/entity-editor/series-section/series-section.tsx, src/server/helpers/middleware.ts, src/server/routes/entity/series.js
**Summary:** 
Reverted some of the relationship editor changes.
=> Revert relationship editor changes

data/test-data.js, test/test-achievement.js, test/test-series-creator.js
**Summary:**
Added tests for series creator achievements.
=> test: add tests for series creator achievements

package-lock.json, package.json, src/server/helpers/diffFormatters/entity.js, src/server/helpers/revisions.ts, src/server/routes/entity/series.js, src/server/routes/revision.js
**Summary**
Added revision diffs for series and relationship atrributes.
=> feat(series,relationship): add revision for series and relationship attributes

src/common/helpers/utils.ts
https://github.com/bookbrainz/bookbrainz-site/pull/690#discussion_r690578719
Pass **`{numeric: true}`** option to **localeCompare.**
```
// by default, "2" > "10"
console.log("2".localeCompare("10")); // 1
// numeric using options:
console.log("2".localeCompare("10", undefined, {numeric: true})); // -1
```
https://github.com/bookbrainz/bookbrainz-site/blob/series-entity/src/common/helpers/utils.ts
=> FIX: Allow sorting with numeric value

src/server/routes/revision.js
Forgot to commit this before merging #626 
Remove the use of the costly .toJSON() function on ORM model, since we only need the BBID from the model.
=> Small refactor of revision page code

src/client/entity-editor/edition-section/actions.ts, src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/edition-section/reducer.ts
This PR deals with BB-621 .
The "page count" field has been taken out of the "physical data" section, i.e., it will be available even if the physical data section is disabled. If eBook is chosen, the physical data section will be disabled. "physical data" section have been fixed into the default editing flow, i.e, the button for showing it has been removed.
https://user-images.githubusercontent.com/56965261/117302540-60ab4b00-ae99-11eb-9173-5716e49f5dae.mov
modified:   src/client/entity-editor/edition-section/edition-section.tsx
modified:   src/client/entity-editor/edition-section/reducer.ts
modified:   src/client/entity-editor/edition-section/actions.ts
Initially we used SHOW_PHYSICAL actions to make changes to the physicalVisible flag. Now, I have changed its name to ENABLE_PHYSICAL and …
=> [BB-621]: Physical data section should be disabled if eBook is chosen

src/client/entity-editor/common/entity-search-field-option.js, src/client/entity-editor/relationship-editor/relationship-editor.tsx
**Summary:**
Do not show **series** entities whose **`entityType`** is not same as the **`baseEntity.type`** in the search results of the relationship editor.
=> FIX: Disallow to add dissimilar entity to series

Dockerfile
I found out the postgres-client package was being removed following removal of packages that are erroneously in the list of build deps (to be removed).
Also made OS release name automatic rather than hardcoded in apt package repo addition.
=> chore: fix postgres client tools installation in Dockerfile

src/client/helpers/utils.tsx
BB-630 : URLs with ~ in edit notes do not get parsed properly
added '~' match in urlRegex
1. src/client/helpers/utils.tsx
=> fix[BB-630]: fix regex to match ~ in url

src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.js, src/server/routes/entity/publisher.js, src/server/routes/entity/series.js, src/server/routes/entity/work.js
fixing BB-458 bug
show  error conflict page when user tries to delete same entity twice.
1. src/server/routes/entity/author.js
2. src/server/routes/entity/edition-group.js
3. src/server/routes/entity/edition.js
4. src/server/routes/entity/publisher.js
5. src/server/routes/entity/series.js
6. src/server/routes/entity/work.js
=> Fix[BB-458]: Showing error conflict page on deleting entity twice

src/client/components/pages/collection.js
The Collection Page Name Section does not have a horizontal rule between Collection Title and Collection Attributes. This makes the design of the page appear somewhat inconsistent.
Here's how the Collection Page looks like: 
Here's how other entities look like: 
Here's how the Collection Page should look like:
Added a Horizontal Rule between the title and attributes of the Collection in collection page
=> fix(CollectionPage): Added Horizontal rule in CollectionPage

src/client/components/footer.js, src/client/components/forms/deletion.js, src/client/components/forms/parts/achievement.js, src/client/components/forms/profile.js, src/client/components/forms/registration-details.js, src/client/components/forms/userCollection.js, src/client/components/pages/about.js, src/client/components/pages/contribute.js, src/client/components/pages/develop.js, src/client/components/pages/help.js, src/client/components/pages/index.js, src/client/components/pages/licensing.js, src/client/components/pages/parts/call-to-action.js, src/client/components/pages/parts/editor-achievements.js, src/client/components/pages/parts/search-field.tsx, src/client/components/pages/parts/search-results.js, src/client/components/pages/privacy.js, src/client/components/pages/registration-auth.js, src/client/components/pages/search.tsx, src/client/components/pages/statistics.js, src/client/containers/layout.js, src/client/input.tsx, src/client/stylesheets/style.less, src/server/helpers/mailer.ts, webpack.client.js
Review time estimate: 20 minutes
There are a number of issues which it's helpful to resolve before moving the site from Bootstrap 3 to Bootstrap 4.
Before submitting the PR that moves to BS4, this PR addresses these issues, fixing a few UI bugs, speeding up webpack compilation time and cleaning up unused code.
Client components and webpack configuration. Excluding whitespace changes, the largest diffs are to src/client/components/forms/userCollection.js and src/client/components/pages/licensing.js.
=> Prepare client components for bootstrap 4

src/server/routes/entity/edition.js
BB-637: When editing edition width, height, depth, and weight fields are locked
I suppose there was typo in variable name  so renamed physicalVisible -> physicalEnable
src/server/routes/entity/edition.js
=> fix[BB-637]: Fixing typo in variable name?

src/server/routes/editor.js
https://tickets.metabrainz.org/browse/BB-551
In user activity graph of editor Monkey, after the current month revisions the graph was showing revisions of year 2015 and 2016  i.e., dates in graph starts from the day of joining but because there were some revisions that were of before the joining date hence dates in graph were not sorted
To make sure the dates are in correct order I changed the start condition of the graph. 
condition is: if the joining date of the editor is greater than the first revision then graph will start from date of first revision otherwise it will start from the joining date.
=> Graph date fix

src/client/components/pages/index.js, src/client/containers/layout.js
- Make the input required in order to search anything.
=> Disable Search for no query entered

src/client/entity-editor/button-bar/button-bar.js, src/client/entity-editor/common/new-date-field.js, src/client/stylesheets/style.less
BB-604: The date picker popper is hidden on small screen devices
( i also notice overflow issue with link button so fixed it as well )
add some css to fix the responsive problem  
1. src/client/stylesheets/style.less
2. src/client/entity-editor/common/new-date-field.js
3. src/client/entity-editor/button-bar/button-bar.js
=> Fix[BB-604]: making datepicker and link button responisve on small screen devices.

src/client/components/pages/entities/annotation.js
BB-636: Show more link should be hidden in small annotations.
Compare span height with parent container for toggling show more button.
1. src/client/components/pages/entities/annotation.js
=> Fix(BB-636): displaying show more button only when necessary

src/client/stylesheets/style.scss
A couple of minor things changed with the migration to Bootstrap4 in #769 
- the date inputs have become much larger (the date input component now fills available space)
- behavior of the navbar items when there isn't enough horizontal space (in very specific conditions: screen width > 992px and < 1091px, on pages other than index)
Just a couple of CSS tweaks did the trick:
- limit date input component width (copied size from pre-migration CSS)
- `white-space: nowrap;` on the menu items
With flexbox, search input will take less space if there is a lack of space instead of the menu item wrapping.
src/client/stylesheets/style.scss
=> Bootstrap4 migration tweaks

src/client/components/pages/parts/call-to-action.js, src/server/routes/entity/series.js
Suggested in https://tickets.metabrainz.org/browse/BB-513
Edition Groups are created automatically when creating an Edition, so there is less point in having this shorcut in the call to action.
However the new Series entity was completely missing.
=> feat(call-to-action): Replace Edition Group with Series

src/client/components/pages/parts/pager.js, src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/entity-merge.tsx, src/client/entity-editor/relationship-editor/relationship-editor.tsx, src/client/entity-editor/relationship-editor/relationship.tsx, src/common/helpers/utils.ts, src/server/helpers/render.ts, src/server/helpers/utils.ts, src/server/routes/collection.js, src/server/routes/collections.js, src/server/routes/editor.js, src/server/routes/entity/entity.tsx, src/server/routes/revisions.js, src/server/routes/search.js, test/src/server/helpers/utils.js
There are some instance in the codebase where from the client-side code we are importing code from the server-side code folder (instead of the existing /common folder).
This can create some issues with Webpack 5 (with [removal of auto-injected NodeJS polyfills](https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed)), and shouldn't be done anyway.
Exhibit A: https://pastebin.com/hymEgHgB
Along the lines of:
```
Module not found: Error: Can't resolve 'assert' in '/Users/Lenore/Work/Brainz/BookBrainz/bookbrainz-site-api/node_modules/@elastic/elasticsearch/api'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a …
```
=> Move common code to /common folder

src/server/routes/entity/edition.js
BB-643: Beta: "Add edition" is not pre-populated from work.
setting initialState in correct place
src/server/routes/entity/edition.js
=> Fix(BB-643): Setting initialState in correct place

src/client/components/forms/deletion.js, src/client/entity-editor/alias-editor/alias-editor.js, src/client/entity-editor/identifier-editor/identifier-editor.js
Tooltips are rendered by default on top of their OverlayTrigger, and for modal headers the tooltips appear mostly off-screen:
Adds `placement="right"` property to OverlayTrigger components that appear in modal headers.
Other OverlayTriggers remain untouched as we don't have the issue mentioned above.
```
src/client/components/forms/deletion.js
src/client/entity-editor/alias-editor/alias-editor.js
src/client/entity-editor/identifier-editor/identifier-editor.js
```
=> fix(bs4): Place tooltips to the right in modal header

src/client/entity-editor/name-section/name-section.js
As reported [in the forums](https://community.metabrainz.org/t/bug-after-changes/575062) the possible duplicate entities are not clickable anymore.
introduced in the Bootstrap v4 migration: 30518cacd058d63f09d54d1b5fff625c254ce294
Simply adding the `action` boolean prop turns the list group item into an anchor tag.
From [react-bootstrap docs](https://react-bootstrap-v4.netlify.app/components/list-group/):
>Toggle the action prop to create actionable list group items, with disabled, hover and active styles. List item actions will render a <button> or <a> (depending on the presence of an href) by default 
This component is the only ListGroup.Item that has an `href` and that we use as a link.
src/client/entity-editor/name-section/name-section.js
=> fix(bs4): Make exactMatches ListGroupItems links

src/client/components/pages/entities/work-table.js
If authorsData is undefined (in case of collections, it will be undefined), the author name column should not be rendered.
check if authorData is defined before trying to render it in the WorkTableRow component
=> fix(Collection): conditionally render author name column in the Work Table component

src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/edition-section/reducer.ts, src/server/routes/entity/edition.js
As [reported on the forums](https://community.metabrainz.org/t/more-serious-bug-concerning-edition-groups/575369/4), when a user creates an Edition with the name pre-filled (for example using the search page call to action), the search for an Edition Group with the same name is not performed automatically, and the user would have to modify the name to trigger it.
With this PR, we perform the search for matching Edition Group server-side and add the results to the initial state before sending the rendered page.
In a separate PR, I will add the same sort of mechanism to search for duplicates when pre-filling the name
=> fix(entity-editor): Edition: search for EditionGroups with same name

src/client/entity-editor/name-section/name-section.js, src/client/entity-editor/name-section/reducer.js, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.js, src/server/routes/entity/publisher.js, src/server/routes/entity/series.js, src/server/routes/entity/work.js
While working on #800 I realized we have the same issue with the duplicate search:
When creating a new entity, the search for possible duplicates is only triggered when when user types in the name input.
When using query parameters to pre-fill the name of a new entity, that doesn't happen, leading to possible dupes.
With this PR we trigger a search for possible duplicates when we render the props to send to the user.
=> feat(entity-editor): search for duplicates when pre-filling name

package.json, src/client/entity-editor/common/language-field.tsx, yarn.lock
The select is crazy slow on older browsers due to issues with filtering the gigantic list of options.
The default filtering of react-select is inefficient
Using the library react-select-fast-filter-options fixes the issue.
It uses js-search under the hood which is more efficient.
src/client/entity-editor/common/language-field.tsx
package.json and yarn lockfile
=> fix(language-select): Fix filtering of language select options

src/client/components/pages/revision.js
In the revision page (for a single revision), URLs in notes are not made into real clickable URLs as is the case with the revision history page (history of revisions for an entity) (See #572)
=> feat(BB-564): Make revision notes links clickable

src/server/routes/merge.ts
In this middleware we exit early if the entity doesn't have a relationshipSet ID.
As a consequence, entity.relationships is not set to an empty array, as is expected by some code down the line, for example here: https://github.com/metabrainz/bookbrainz-site/blob/38e083e90c6592e3f4f5597a1a2a2a5b355759b4/src/client/entity-editor/series-section/series-section-merge.tsx#L86
Trying to spread `undefined` results in an error thrown which currently crashes the server — which is a separate issue.
=> fix(merging): Default to empty relationships array in middleware

src/client/components/pages/entities/work-table.js
We were using `<tr>` elements inside `<td>`s to show a list of authors ([in `renderAuthors` method](https://github.com/metabrainz/bookbrainz-site/blob/b919b95596ab5526a06831f351036278f3254dfb/src/client/components/pages/entities/work-table.js#L37)), but that breaks the HTML table structure and weird stuff happens to the page structure (see https://community.metabrainz.org/t/bug-with-adding-a-work-to-an-edition)
Using `<div>`s instead allows us to keep each author on a separate line but does not break the page structure.
=> fix(entity-editor): Fix WorkTable HTML structure

src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/edition-section/reducer.ts
https://community.metabrainz.org/t/lag-between-typing-and-appearance-of-information-in-annotation-section-of-editions/579426
Introduced in commit 7d02163, using an Immutable.List instead of a plain array to store `matchingNameEditionGroups` in the redux state introduced a  huge slowness in state deserializing which impacted the whole entity editor (when creating/editing Editions only).
The page slows down to a crawl if you trigger lots of state updates, for example writing text in the annotation textarea.
Reverting these changes to fix the issue.
=> fix(entity-editor): [BB-661] Remove slow deserialization in redux state

src/client/entity-editor/identifier-editor/identifier-row.tsx, src/client/entity-editor/identifier-editor/reducer.ts, src/client/entity-editor/validators/common.ts, src/common/helpers/utils.ts
In this PR, I am making ISBN detection more strict by verifying its check digit, disabling switching type after user manually selected it and disabling new ISBN row addition(temporary).
=> Fix(Identifier-Editor): Improve identifier editor behavior for ISBNs

src/client/entity-editor/alias-editor/alias-editor.js, src/client/entity-editor/common/language-field.tsx, src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/name-section/name-section.js, src/client/entity-editor/work-section/work-section-merge.tsx, src/client/entity-editor/work-section/work-section.tsx
Languages are not sorted according to frequency after using fast-filter
Sort options manually after filtering
language-field
=> Fix(languages): Sort language options after fast filter

docker-compose.yml, scripts/create-db.sh, scripts/database-init-docker.sh, scripts/download-import-dump.sh
1. Follow [guidelines for docker-compose file](https://github.com/metabrainz/guidelines/blob/master/Docker.md#publishing-ports)
2. Simplify database creation (use postgres image env variables instead of running a script)
3. Make the database init script a bit more reusable
=> chore: Docker setup improvements

src/client/entity-editor/common/entity-search-field-option.js, src/client/entity-editor/edition-section/actions.ts, src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/edition-section/reducer.ts, src/client/entity-editor/validators/edition.ts, src/client/helpers/entity.tsx, src/server/routes/entity/edition.js, test/src/client/entity-editor/validators/test-edition.js
BB-655: Allow Publisher field to have multiple publishers
=> Feat(edition): Allow multiple publishers for a single edition

src/server/app.js, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.ts, src/server/routes/entity/publisher.js, src/server/routes/entity/series.js, src/server/routes/entity/work.js
The middleware `decodeUrlQueryParams` was introduced in #819 to fix an issue with encoding of names passed to an entity create route (see [BB-646](https://tickets.metabrainz.org/browse/BB-646)).
We didn't realize at the time before deploying to beta that the entity search component (used for example in the relationship editor) stopped working.
This is because the search endpoint is called with multiple type arguments of the same name (`…&type=author&type=work`) which was previously parsed as an array by ExpressJS.
The `decodeUrlQueryParams`  middleware changed that to a string or comma separated values ("author,work") instead of the expected array.
To fix this, let's apply the decodeUrlQueryParams middleware only for required `/$entityType/create` routes
=> Fix autocomplete search endpoint

sql/migrations/2022-06-28-views/down.sql, sql/migrations/2022-06-28-views/up.sql, sql/schemas/bookbrainz.sql
This is tied to the CritiqueBrainz-BookBrainz integration project.
Using the views is particularly helpful in the CB codebase since  it is in python and they cannot use our JS ORM.
So we are adding some columns to the views for each entity (alias name and sort name, disambiguation content, entity type labels, etc.)
=> Add useful columns to entity views

sql/migrations/2022-07-07-identifier-templates/down.sql, sql/migrations/2022-07-07-identifier-templates/up.sql
These can be used to reconstitute a URL to the resource on the front-end.
We need them added to the database because they will now be used by CritiqueBrainz and we don't want to duplicate the code in both codebases.
The database table was already set up to have a template, which we previously decided not to use.
We will have to get rid of the code in src/client/components/pages/entities/identifiers-links.js while making sure to preserve our [one special use-case](https://github.com/metabrainz/bookbrainz-site/blob/60ff054647e824f5cd2146ca132db22099ab92b9/src/client/components/pages/entities/identifiers-links.js#L65)
=> chore(sql): Update identifier types' display templates

src/client/entity-editor/alias-editor/alias-row.js
Fix language display issue in alias-row
=> fix(language-select): Correctly format language options for alias row

src/server/helpers/entityRouteUtils.tsx, src/server/helpers/middleware.ts, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.ts, src/server/routes/entity/process-unified-form.ts, src/server/routes/entity/publisher.js, src/server/routes/entity/series.js, src/server/routes/entity/work.js, test/src/server/routes/unifiedform.js, test/test-helpers/create-entities.js
Since now we need to edit entity for use cases like adding relationships for work with author, /create/handler POST route should support that as well.
This route expect client to send ~complete state of existing entity with~ required changes only.
Also passing `id`  (bbid of entity), `__isNew__`   (falsy for existing entity) attributes is mandatory with entity state.
Entity state must include submission note for the revision.
src/server/routes/entity/process-unified-form.ts
=> Feat(route): Edit exisiting entity through unified form POST route

src/client/entity-editor/author-credit-editor/author-credit-section.tsx, src/client/entity-editor/edition-group-section/edition-group-section.tsx, src/client/entity-editor/edition-group-section/reducer.ts, src/client/entity-editor/edition-section/edition-section.tsx
Edit button on AC section doesn't work for edition-group entity form.
Add AC modal state in editionGroupSection.
=> Fix(AC): Handle AC modal state for editionGroup entity

src/client/components/author-credit-display.js
We have two different situations for Author Credits display component: one is on the edit page when adding a new AC and the other is on the entity display pages displaying an existing AC.
Depending on which case we are looking at, the author used to construct the AC will not have the same shape, and the author BBID in particular will not be in the same place.
This results currently on broken AC links (href = `/author/undefined`) on the entity display pages (but working for edit pages).
=> Fix(AC): Fix author credit link

src/server/helpers/achievement.js, src/server/routes/editor.js, test/test-fun-runner.js, test/test-marathoner.js
[BB-680](https://tickets.metabrainz.org/projects/BB/issues/BB-680): Fun runner and Marathoner achievements are broken
Currently, we just return the number of distinct (by date) revisions within specified interval but what we actually want is number of consecutive revisions starting from today upto to given interval. this PR does exactly that. 
_note: we might be able to use some sql magic here but i'm not sure how we would do that._
src/server/helpers/achievement.js
=> Fix(achievements): count consecutive days for timed achievements

package.json, src/client/entity-editor/relationship-editor/reducer.js, src/client/entity-editor/relationship-editor/relationship-editor.tsx, src/client/entity-editor/relationship-editor/relationship-section.tsx, src/client/entity-editor/relationship-editor/types.ts, src/client/entity-editor/series-section/actions.ts, src/client/entity-editor/series-section/reducer.ts, src/client/entity-editor/series-section/series-editor.tsx, src/common/helpers/utils.ts, src/server/helpers/entityRouteUtils.tsx, src/server/routes/entity/entity.tsx, src/server/routes/entity/work.js, src/server/routes/merge.ts, test/src/server/routes/relationship.js, yarn.lock
Reference ticket [BB-538](https://tickets.metabrainz.org/browse/BB-538) 
Since we use old relationship items to generate the difference array of allRemovedItems & allAddedItems, this cause issue where we don't have updated rel items. 
We can just use two new attributes on rel to track removed and added items, this will ensure difference array is independent of old rel items.
Since Orm function need some changes to support this workflow, i will be creating similar PR there.
Edit: [PR](https://github.com/metabrainz/bookbrainz-data-js/pull/289)
=> Fix(BB-538): Allow concurrent relationship edits

package.json
I've been hitting some weird issue with the build workflow failing at postinstall step.
This is apparently due to the docker user's HOME path being set to `/root` instead of the home for the user `node`.
The NPM postinstall step was being run, which somehow was breaking with error code 243, apparently related to permission issues with the cache directory.
See https://github.com/npm/cli/issues/4769
Removing the postinstall step (which is not required and left over from way back when) solves the issue, but some investigation still needs to be done to figure out why the user's home is not set right in the docker image (or if we are using the wrong user somehow).
=> chore: Fix CI builds

src/client/components/pages/entities/author.js, src/server/routes/entity/entity.tsx
This PR fixes two behavior:-
1. CBRevisionModal causes the site to crash on the deleted entity.
2. Revision Parent doesn't update on deleting an entity.
=> Fix: Deleting entity crashes the site

src/client/helpers/utils.tsx
This PR addresses ticket BB-662.
Initially, we were adding an `https://` even if it was already present in the string, now I have added a check.
I have also improved the regex we were using, as I feel it was a bit insufficient and antiquated. I took help from [this](https://stackoverflow.com/a/71734086), and I think it works a lot better and is somewhat cleaner also.
=> [BB-662]: URLs are turned into malformed links

src/client/stylesheets/style.scss
This PR addresses [BB-698](https://tickets.metabrainz.org/browse/BB-698). Text in the annotations is breaking after any character (line-break: anywhere) rather than at the word level.
Overriding the `word-break: break-all` property which is inherited due to the `pre` element.
=> fix([BB-698]): Line break at the character level in annotations

package.json, src/api/app.js, yarn.lock
We use 'legacyMode' in order to play well with the connect-redis package (which links ExpressJS sessions to Redis). This also means we don't need to change the structure of the `createClient` args object. See  https://github.com/tj/connect-redis/pull/337#issuecomment-981754350
Also of interest, the redis package changelog: https://github.com/redis/node-redis/blob/redis%404.0.0/packages/client/CHANGELOG.md
=> chore: Update redis package to v4

.gitattributes
Windows systems cloning repo would insert CRs to end of lines. This causes shell scripts executing in WSL to fail.
Enforce Unix end-of-line convention; IDEs can handle this quite well.
Git client will avoid adding CRs, and will strip CRs from text files on commit.
=> Enforce Unix end-of-line convention.

src/client/components/pages/entities/author.js, src/client/components/pages/entities/edition-group.js, src/client/components/pages/entities/series.js, src/client/components/pages/entities/work.js
We can't load a deleted entity page, the website just times out and returns a 504.
Looking at the logs, we see:
```
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'name')
at WorkDisplayPage (/home/bookbrainz/bookbrainz-site/lib/client/components/pages/entities/work.js:143:37)
```
Looking at the WorkDisplayPage component, the issue is pretty clear: we are trying to pass `entity.defaultAlias.name` as a prop to the CBReviewModal, but on a  deleted entity defaultAlias will be undefined, resulting in the error above.
The same goes for the other reviewable entities.
Solution: wrap the modal in the same condition we use elsewhere in the same pages: `{!entity.deleted && <CBReviewModal …`
There might be another issue described in the ticket, but at least the 504 issue …
=> BB-707: Don't create CBReviewModal for deleted entities

package.json, src/api/app.js, src/server/app.js, src/server/routes/auth.js, yarn.lock
I borked the redis connection in #932 and needed to revisit redis.
In the meantime, connect-redis v4 came out which removes the need for legacyMode in node-redis.
This PR updates the required bits and pieces to update the whole chain.
Also see https://github.com/redis/node-redis/blob/redis%404.0.0/docs/v3-to-v4.md and https://github.com/tj/connect-redis/releases/tag/v7.0.0
=> Update connect-redis 

src/client/entity-editor/name-section/name-section.js
Found while updating the developer docs in https://github.com/metabrainz/bookbrainz-dev-docs/pull/13.
I renamed all occurrences of this typo using VS Code variable renaming feature and did a global search for it to ensure that I haven't missed any.
=> style: fix typo in searchForMatchingEditionGroups

src/client/components/pages/parts/call-to-action.js, src/server/helpers/middleware.ts, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.ts, src/server/routes/entity/publisher.js, src/server/routes/entity/series.js, src/server/routes/entity/work.js
Double encoding the seeding query parameters (e.g. http://localhost:9099/author/create?name=Rhythm%2520%2526%2520Beauty%253A%2520The%2520Art%2520of%2520Percussion) is entirely unnecessary.
Properly encode the query parameter once (e.g. http://localhost:9099/author/create?name=Rhythm+%26+Beauty%3A+The+Art+of+Percussion).
Now we can also drop the `decodeUrlQueryParams` middleware (which was undoing the second encoding pass), Express.js is already doing one decoding pass for us automatically.
"Are we missing an entry?" section of the search results page.
=> fix(call-to-action): properly encode query parameters once

src/server/helpers/middleware.ts, src/server/routes/revision.js
When a revision page is requested with a crafted id, for example https://bookbrainz.org/revision/whynot, a PostgreSQL query is made.
It mainly adds a small unneeded load to the database server.
Adding a middleware function which checks whether the parameter id is numeric or not.
=> BB-692: Website server doesn't check revision id format before querying PostgreSQL

src/client/components/pages/entities/links.js, src/client/components/pages/entities/related-collections.js
Previously the list of collections was displayed inline with the heading:
Wrap heading and list into a `<div>` container which serves as flex item of the `<Row>` flex-box:
I'm wondering whether I should have used a `<Col>` instead of a `<div>` which seems to be the semantically correct way. For now I have decided against it because the "Relationships" and "Identifiers" sections directly above are also using a `<div>` which results in [less unused space](https://user-images.githubusercontent.com/52860029/223233846-8ccd9bc2-6a0e-4777-a05c-7a826547e4d5.png) to the left than a `<Col>` (which is used by "Annotation" and the "Works" section of an Edition).
But I think we should make this consistent in the end?
Another related question: Should we really show the headings for empty sections? I …
=> fix(display): always use Col as container inside Row flex-boxes 

src/client/components/forms/registration-details.js, src/client/entity-editor/author-section/author-section.tsx, src/client/entity-editor/edition-group-section/edition-group-section.tsx, src/client/entity-editor/edition-section/edition-section.tsx, src/client/entity-editor/publisher-section/publisher-section.tsx, src/client/entity-editor/work-section/work-section.tsx
BB-690
Reset functionality for _Select_ elements  in the +Add sections, like "Type", "Format" or "Status"
Modified 6 files that handle 6 different pages in the +Add category. Added an attribute for _Select_ elements that enables the possibility to unset an option.
=> BB-690: added unset functionality for dropdowns

src/client/components/pages/entities/edition-table.js, src/client/components/pages/entities/publisher.js, src/client/helpers/entity.tsx, src/server/routes/entity/publisher.js
It would be quite informative to see the author(s) of an edition in the list of editions for a given publisher. This PR addresses [BB-709](https://tickets.metabrainz.org/browse/BB-709)
Added a column to display the author credits using the already existing AuthorCreditDisplay component.
=> BB-709: Add Author Credits column in publisher editions listing

test/src/server/routes/revision.js
This PR is a continuation of [this PR](https://github.com/metabrainz/bookbrainz-site/pull/931) and adds a test for the same.
=> BB-692: Add test for checkValidRevisionID

src/client/helpers/utils.tsx
[BB-741](https://tickets.metabrainz.org/browse/BB-741): Regular expression error in Safari
RegExp lookbehind expressions were unsupported by Safari until version 16.4 from March 2023.
Add missing https:// prefixes to plain text URLs without using a lookbehind expression.
This should have been the only occurrence of such an expression in our codebase.
All pages which display annotations or revision notes, but apparently it broke the whole site's client JS in Safari (which I couldn't verify without having an installation of Safari).
=> BB-741: Add https:// prefix without using a lookbehind expression

src/server/helpers/i18n.ts
The HTTP Accept-Language header can also be undefined which causes a type error.
Treat this case the same way as an empty (`''`) or wildcard (`'*'`) header which both return an empty array of language codes.
Server routes which are loading Wikipedia extracts.
=> fix(core): handle undefined Accept-Language header

src/client/components/pages/entities/series-table.js, src/client/components/pages/parts/collections-table.js, src/client/components/pages/parts/editor-profile.js, src/client/components/pages/parts/revisions-table.js, src/client/components/pages/parts/search-results.js, src/client/components/pages/statistics.js
[BB-714](https://tickets.metabrainz.org/browse/BB-714)
The width of tables on the Webkit-based browser are broken.
The width of the columns is defined using Bootstrap CSS classes, which is not working on Webkit.
Setting the column sizes using the width attribute in percentages solves the issue.
All tables rendered on the Bookbrainz website that use the `col-md` class name to specify the width.
=> BB-714: Fix search results page on Safari

data/test-data.js, test/common.js, test/test-achievement.js
Problem
[BB-673](https://tickets.metabrainz.org/browse/BB-673):
Across the codebase, we have asynchronous code written using promises, which is hard to read and to maintain and error-prone.
Solution
All this code was rewritten using the async/await syntax.
Areas of Impact
The changes were reflected in test/common.js
=> BB-730: Rewrite test files using async/await syntax

src/client/components/pages/entities/related-collections.js
3feb7142977b652015456838ae6d7178e7068330 inserted a non-breaking space at the end of the line which is not automatically stripped, but treated as text. Because the next line also starts with text, an additional space is inserted to separate "words" (which was unwanted in this case).
=> fix(display): prevent two consecutive spaces in JSX

src/client/components/pages/admin-panel-search.tsx, src/client/components/pages/parts/admin-panel-search-results.tsx, src/client/components/pages/parts/privs-edit-modal.js, src/common/helpers/error.js, src/server/helpers/auth.js, src/server/routes/adminPanel.js, src/server/routes/editor.js, src/server/routes/entity/author.js, src/server/routes/entity/edition-group.js, src/server/routes/entity/edition.ts, src/server/routes/entity/publisher.js, src/server/routes/entity/series.js, src/server/routes/entity/work.js, src/server/routes/merge.ts, src/server/routes/reviews.js, src/server/routes/unifiedform.ts, test/src/server/routes/editor.js, test/src/server/routes/entity/author.js, test/src/server/routes/entity/edition-group.js, test/src/server/routes/entity/edition.js, test/src/server/routes/entity/publisher.js, test/src/server/routes/entity/series.js, test/src/server/routes/entity/work.js, test/src/server/routes/merge.js, test/src/server/routes/unifiedform.js, test/test-helpers/create-entities.js
This PR adds a middleware to facilitate privilege-based access to certain routes.
=> feat(Admin System): Add middleware for securing routes according to privs

src/client/components/pages/search.tsx
Using a stored reference to the PagerElement react component, we can manually call its triggerSearch function that is usually called when the input or query params change (i.e. browser navigation for example).
That way clicking on the "search" button will actually perform the search again even if the query hasn't changed.
Supersedes #884
=> BB-681: refresh search results on button press if same query

src/client/entity-editor/work-section/work-section.tsx
Following #989, this PR fixes and improves some details of displaying a tooltip and the description of the currnetly selected work type:
Tooltip (was not working for some reason):
Selection description:
=> feat: Improve work type selection

src/client/components/forms/registration-details.js
As reported in https://community.metabrainz.org/t/cant-sign-up-with-bookbrainz/652424/3 , the registration form sohuld allow for the gender select to be optional. 
Currently, the code to access the value of the gender select input assumes one is selected, and throws an error in the console when that is not the case, preventing the registration from completing successfully, but also not giving any visual indication that something is wrong.
=> fix: optional gender in registration form

src/client/helpers/utils.tsx
BB-749: Links that include "https://" as part of the non-protocol of the URL in Annotations break.
Modified `urlRegex` regular expression.
The changes were reflected in `src/client/helpers/utils.tsx`
=> BB-749: Links that include "https://" as part of the non-protocol of the URL in Annotations break.

package.json, src/client/components/input/drag-and-drop.tsx, src/client/components/pages/entities/wikipedia-extract.tsx, src/common/helpers/utils.ts, src/common/helpers/wikimedia.ts, yarn.lock
In https://github.com/metabrainz/bookbrainz-data-js/pull/309 a few types have been renamed to be more consistent, this PR does the necessary changes for types which have already been used by the server.
~TODO: Bump version of bb-data once a new release of it is available on npm.~
=> TypeScript migration of the ORM

package.json, test/src/server/helpers/collections.js, test/src/server/helpers/revisions.js, test/src/server/routes/collection.js, test/test-helpers/create-entities.js, yarn.lock
1. Remove the UUID package in favor of the built in functionality in the faker package
2. Remove duplicate faker package: we were using `faker` v4 as well as the more recent `@fake-js/faker` side by side for some reason.
=> Test dependencies: replace UUID package and duplicate faker package

src/client/components/pages/help.js
Michael Scott’s *The Secrets of the Immortal Nicholas Flamel – The Alchemyst* is a fictional novel, not a biography.
```diff
-The Alchemyst (Nicolas Flamel biography) by Michael Scott
+The Alchemyst (YA novel featuring Nicolas Flamel) by Michael Scott
```
=> docs(static): fix mischaracterization of a book mentioned in an example

src/client/components/pages/entities/cbReviewModal.tsx
[BB-718: CritiqueBrainz auth endpoint is called server-side](https://tickets.metabrainz.org/browse/BB-718?filter=11910)
The conditional check - ```typeof window !== "undefined"``` ensures that the ```getAccessToken``` method is only called when the code is executed in a browser environment (client-side), preventing the unnecessary call to the authentication endpoint on the server-side.
The changes were reflected in ```src/client/components/pages/entities/cbReviewModal.tsx```
=> BB-718 CritiqueBrainz auth endpoint is called server-side

src/client/components/input/drag-and-drop.tsx, src/client/components/pages/parts/editor-achievements.js, src/client/controllers/editor/achievement.js, src/server/routes/editor.tsx
[BB-722](https://tickets.metabrainz.org/projects/BB/issues/BB-722): Display already selected achievements in Edit Achievement Page
=> BB-722: Display already selected achievements in Edit Achievement Page

src/client/entity-editor/entity-editor.tsx
BB-758
Using anchor tag I added a link inside the heading of entity in editor page , see the screenshot . A direct link to entity page from entity editor page makes it very  convenient while comparing the fields being edited with the original ones 
https://github.com/metabrainz/bookbrainz-site/assets/97682967/e4d297f3-7e27-40a2-9c79-66d57584226f
This PR effect the entity-editor page section of the codebase
=> fix BB-758 : Link from edit page to entity page

src/client/components/pages/parts/add-to-collection-modal.js
Reported in https://community.metabrainz.org/t/creating-a-new-collection-doesnt-work/680552
The privacy options select component is being shown inside the modal body but after the scroll break, meaning by default without knowing to scroll down users won't see the options and it will look broken. Setting the menuPosition prop to "fixed" means the options component is shown over the rest of the content, which is much better.
Before:
After:
=> collection modal: Set fixed position of privacy select

src/client/components/pages/parts/search-results.js, src/common/helpers/search.js, src/common/helpers/search.ts, src/server/helpers/collectionRouteUtils.js, src/server/routes/editor.tsx, src/server/routes/entity/entity.tsx, src/server/routes/entity/process-unified-form.ts, src/server/routes/register.js
This PR came about after #740 started causing the website to crash when editing/creating Work entities.
I took this opportunity to make the search indexing more reliable by improving error catching.
While rewriting some of that code, I realized we are indexing a loooot of fields that we have no reason to index.
First of all, some internal ORM fields that are output by default when serializing to JSON.
Then the entire entity info is stored inn ElasticSearch, while on the other hand we load entities afresh from the DB based on the search results hits, which means at the moment we do absolutely nothing with all this entity info other than take disk space, slow down indexing and transferring too much data.
So we are now "cleaning" the documents before indexing them, i.e. keeping only the …
=> feat: Improve search indexing reliability

package.json, yarn.lock
This major update did break something (breaking the book wizard page) and I didn't realize despite testing.
The issue in question is as described here: https://github.com/reduxjs/react-redux/issues/1992
Presumably something related to [`use-sync-external-store` library](https://www.npmjs.com/package/use-sync-external-store), a shim for React.useSyncExternalStore.
See https://github.com/reduxjs/react-redux/releases/tag/v8.0.0
For some reason, compiling with webpack in production mode results in that page-breaking error, while compiling in development mode runs fine.
=> chore(deps): Revert react-redux package upgrade

develop-api.sh, develop.sh, docker-compose.api.yml, docker-compose.yml, scripts/database-init-docker.sh, stop.sh
Depending on the version of docker, we want to call either `docker-compose` or `docker compose`.
See https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/
Version detection code copied from ListenBrainz
Also removes the 'version' argument in docker-compose files, which is now deprecated.
=> Updates for Docker compose v2

src/client/entity-editor/common/entity-search-field-option.js
Hi there,
While searching for issues to contribute to Bookbrainz I found `BB-793` for improving the UX of the add authors to collection form, I have found it a good start for a beginner such as me so I have started to work to know where is the problem and how to solve it.
The first time, I was trying to improve the search field element in authors to collection form such as the `BB-793` issue, then I found that the search field element at more places such as add collaborators to the collection as you can see in the images below.
The first solution was to add a CSS class to handle the search field width to be suitable to screen width and provide a good UX, but I have found that this has happened but no effect we can notice. 
The class `Select` is responsible for handling the width of the …
=> fix(BB-793): Improve the UX with the search field option entity

src/client/components/pages/statistics.tsx, src/client/helpers/utils.tsx, src/types.ts
The bookbrainz project has been gradually adopting typescript. Typescript can help us prevent the code base more type safe and boost collaboration
Refactored the statistics and any related functions to typescript.
Added the type _EditorType which can easily be imported in  the ts files wherever necessary 
statistics page
=> refactor(statistics) to typescript

src/client/unified-form/cover-tab/isbn-field.tsx, src/client/unified-form/interface/type.ts
BB-764: On the unified form, ticking and then unticking the "Automatically add ISBN" checkbox results in the generated ISBN to be left over in the "edit identifiers" modal.
Unchecking should remove the auto-generated ISBN.
With the present code, what happens is that when the user checks the box for the first time, an action is dispatched to have the auto generated ISBN in the list of identifiers, but when he unchecks again, there was no direction to remove the added identifier. Hence, I have used this already defined removeIdentifierRow action:-
It requires rowId as a parameter, which we get using the addAutoIdentifier:-
After changes:-
https://github.com/metabrainz/bookbrainz-site/assets/116253210/ecfc1a2b-2f7e-45f0-817a-cc77243a27d9
src/client/unified-form/cover-tab/isbn-field.tsx …
=> BB-764: Unified form ISBNs bug

src/server/helpers/middleware.ts
This broke in https://github.com/metabrainz/bookbrainz-site/commit/d44d67a1e4ad54302ae3f0230cd77d402d253585
Untested, but this is the same function with which all other occurrences were replaced in the above commit. Should have been the last occurrence.
=> fix(helpers): Replace deleted utility by lodash function

src/client/components/pages/admin-panel-search.tsx, src/client/components/pages/searchAdmin.tsx, src/client/containers/layout.js, src/client/controllers/admin/searchAdmin.tsx, src/common/helpers/search.ts, src/server/routes.js, src/server/routes/search.tsx, src/server/routes/searchAdmin.tsx, test/src/api/routes/test-search.js, test/src/server/routes/collection.js, webpack.client.js
This PR fixes a few issues with search indexing:
- Allows indexing each entity type separately
- indexing Works also indexes Authors since we index the work's authors too
- Adds an admin panel page for search with buttons to index each entity:
- Fetch by chunks of 50.000 entities at a time from the database, otherwise the postgres request fails with `bind message has XXXXX parameter formats but 0 parameters` when fetching aliases (maximum 65535 parameters)
- Make the search indexing file typescript, fixes some potential issues
- Misc bug fixes
=> Search admin and indexing improvements

src/client/components/author-credit-display.tsx, src/client/entity-editor/author-credit-editor/actions.ts
For some reason we were not sorting the Author Credit names by their position attribute, and until recently that has not been an issue.
However recently this changed and we have seen issues with the order of items, not just in ACs but also in the order of Works for example ([see forum](https://community.metabrainz.org/t/order-of-works-in-editions-is-not-static-anymore/695814/3))
Author Credits are now sorted with the stable order we are expecting.
While in there, I took the opportunity to make that file a typescript file and fixed a typo in a TS type.
=> BB-803: Sort author credits by their position

src/common/helpers/search.ts, src/server/routes/search.tsx
Broke the search autocomplete endpoint in #1093  when I forgot we can use an array of types in some search endpoints, and calling `toString` on the array of types results in a comma separated joined string which is not recognized as an entity type
=> Fix search entity type

src/client/components/pages/import-entities/author.js, src/client/components/pages/import-entities/discard-import-entity.js, src/client/components/pages/import-entities/edition-group.js, src/client/components/pages/import-entities/edition.js, src/client/components/pages/import-entities/footer.js, src/client/components/pages/import-entities/publisher.js, src/client/components/pages/import-entities/work.js, src/client/components/pages/parts/recent-import-results.js, src/client/controllers/import-entity/discard-import-entity.js, src/client/controllers/import-entity/import-entity.js, src/client/controllers/import-entity/recent-imports.js, src/server/routes/entity/entity.tsx, src/server/routes/import-entity/import-routes.tsx, src/server/routes/import-entity/transform-import.js
Continuation of #1096
- Approval of import is now working thanks to https://github.com/metabrainz/bookbrainz-data-js/pull/319
- Loads author genders to make the entity editor load for the "Edit & Approve" action
(Similar adjustments might be necessary for the other entity types, but currently we are only importing authors)
- Fixes a search indexing related type error (but search indexing still has not been fixed, as we agreed)
- Fixes HMR for the import pages
- More Bootstrap migration changes and layout fixes
The changes in 14340385d75426fd45d7bfe8d89b36cd7f487298 and f289c7189f6e58f0c40c2f57cda2f3f485cabb6b may have not been relevant in the end, but I spotted these inconsistencies before I fixed the real issues in the ORM.
=> Make approval of imported entities work & other improvements

sql/migrations/2024-07-17-annotation-revision-id/down.sql, sql/migrations/2024-07-17-annotation-revision-id/up.sql, sql/schemas/bookbrainz.sql, src/client/components/pages/entities/annotation.js, src/client/entity-editor/annotation-section/annotation-section.js
Rebased version of #1105 
Also see https://github.com/metabrainz/bookbrainz-data-js/pull/320
For imported entities, we do not keep a history of all modifications.
As a result, editing import_* entities is not tied to any revisions.
This is an issue for annotations, whose `last_revision_id` column does not currently accept NULL values.
These small changes allow entering a row in the `annotation`table with `last_revision_id = NULL`, and ensure the website does not trip up if the value is missing (it is used to display the last modification time and link to the revision)
Before: 
After:
=> chore: Allow annotation revision ids to be null (rebased)

.eslintrc.js, sql/migrations/import/up.sql, sql/schemas/bookbrainz.sql, src/client/components/pages/import-entities/author.js, src/client/components/pages/import-entities/edition-group.js, src/client/components/pages/import-entities/edition.js, src/client/components/pages/import-entities/publisher.js, src/client/components/pages/import-entities/work.js, src/client/helpers/import-entity.js, src/server/helpers/importEntityRouteUtils.ts, src/server/helpers/middleware.ts, src/server/routes/import-entity/edition-group.js, src/server/routes/import-entity/import-routes.tsx, src/server/routes/import-entity/transform-form.js, src/server/routes/import-entity/transform-import.js
Display annotations for all types of imported entities and preserve the annotation during the whole "Edit & Approve" process.
The corresponding changes for the "Approve" action are in https://github.com/metabrainz/bookbrainz-data-js/pull/321.
=> Display and preserve annotation of imported entities

.eslintrc.js, sql/migrations/import/up.sql, sql/schemas/bookbrainz.sql, src/client/components/pages/entities/series.js, src/client/components/pages/import-entities/author.js, src/client/components/pages/import-entities/edition-group.js, src/client/components/pages/import-entities/edition.js, src/client/components/pages/import-entities/index.js, src/client/components/pages/import-entities/publisher.js, src/client/components/pages/import-entities/series.js, src/client/components/pages/import-entities/work.js, src/client/entity-editor/series-section/series-section.tsx, src/client/helpers/import-entity.js, src/common/helpers/utils.ts, src/server/helpers/importEntityRouteUtils.ts, src/server/helpers/middleware.ts, src/server/routes/import-entity/edition-group.js, src/server/routes/import-entity/import-routes.tsx, src/server/routes/import-entity/index.js, src/server/routes/import-entity/series.js, src/server/routes/import-entity/transform-form.js, src/server/routes/import-entity/transform-import.js
On top of #1107 (diff: https://github.com/kellnerd/bookbrainz-site/compare/import-annotation...import-series)
Adds the missing routes, pages and data transformation functions for imported series.
Since imported entities can't have relationships yet, we have to handle the case that a series has no defined items (which wasn't necessary for regular series).
And I forgot to add the item entity type to the SQL view in one of my previous PRs.
----
Since the necessary changes to make editing and approval of edition imports work are very minor, I have included these here as well.
=> Support series imports & Fix edition imports

.github/workflows/ci.yml
upload-artifact v2 is now deprecated and fails the workflows.
See https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> chore: Update upload-artifact to v4

package.json, yarn.lock
Update ExpressJS package to 4.21.1
https://github.com/expressjs/express/releases/tag/4.21.1
Fixes CVE-2024-47764
=> chore: Update express package

package.json, src/client/entity-editor/series-section/actions.ts, yarn.lock
An unnecessary package that is causing trouble when dependabot tried to update it (See #1039).
Considering it is used only in this one case in one file and only saves one whole line of code, I am removing the dependency.
=> chore: Remove dependency to array-move package

package.json, yarn.lock
Updates the dependency `send` to 0.19.0, which fixes a vulnerability that dependabot can't seem to find the update for: https://github.com/metabrainz/bookbrainz-site/security/dependabot/65
=> chore: Update serve-static to 1.16.1

package.json, yarn.lock
Update to version to 1.18.1 fixes vulnerability https://github.com/metabrainz/bookbrainz-site/security/dependabot/66
=> chore: Update express-session dependency 

CONTRIBUTING.md
BB-834
The link to the jsdoc homepage (http://usejsdoc.org) is deprecated and leads to a spam site.
Updated the link to the new jsdoc homepage (https://jsdoc.app)
./CONTRIBUTING.md file changed
=> docs: replaced deprecated jsdoc link leading to spam site with updated jsdoc homepage link.

package.json, yarn.lock
Fixing https://github.com/metabrainz/bookbrainz-site/security/dependabot/68 and https://github.com/metabrainz/bookbrainz-site/security/dependabot/69
Affected dependencies: express, sinon, mocha
Not the most critical, considering sinon and mocha should not be used in production, but nevertheless deserving of closing those tickets appropriately.
=> Chore: Fix security issues

Dockerfile, src/client/components/pages/externalService.js, src/server/routes/collection.js, src/server/routes/editor.tsx, src/server/routes/externalService.js, src/server/routes/reviews.ts, src/server/routes/type-editor/identifier-type.tsx, src/server/routes/type-editor/relationship-type.tsx
[BB-813](https://tickets.metabrainz.org/browse/BB-813)
The cbReviewModal is triggering a post request whose URL is being 
stored and used as a redirection link later on during authentication.
This creates a redirection bug when a user attempts to sign in on any of the pages with said cbReviewModal.
- work
- edition groups
- authors
- series
The route handler for /critiquebrainz/refresh has been updated to use
isAuthenticatedForHandler (which authenticates without redirecting) instead of isAuthenticated which was filling in the redirect link.
4 Additional Route Handlers have been updated to protect against the same bug.
Here's a [Google Document with images](https://docs.google.com/document/d/1rCKs1Yp_Gs5eRJKHCpbxsojq6M2adevqOMN5y6Ksj-Q/edit?tab=t.0#heading=h.tn1b6d5bh6w0) of user testing …
=> fix(auth): replaced authentication middleware with one intended for post requests. (Note: docker node 18 -> 20)

Dockerfile, src/client/components/pages/entities/cbReviewModal.tsx
[BB-838](https://tickets.metabrainz.org/browse/BB-838)
The "react-simple-star-rating" does not appear to reflect immediate state changes.
The Rating component has been updated to directly set "value" in response to state changes instead of the "ratingValue" prop, now immediately displaying the star value selected by the user.
- cbReviewModal.tsx altered. 
- Ratings show correctly on CritiqueBrainz and in the ReviewCard displayed on the work.
=> fix: cbReviewModal star rating now sets on the first click (Note: Docker Node 18->20)

src/client/stylesheets/style.scss
- **Issue BB-683**: Users cannot use arrow keyboard keys in language/select/search fields
- Two specific problems were identified:
1. PgUp and PgDn keys appeared non-functional when focused in the text input
2. HOME and END keys stopped working after language selection was made
Added necessary styling improvements to fix the following:
- PgUp and PgDn keys now work properly when navigating options
- Added background highlighting for the selected language option
- Added visual focus indicator when using PgUp/PgDn to navigate through language options
Regarding HOME and END keys:
- These keys are reserved by React-Select library for specific functions
- HOME and END still work correctly when typing (before selection)
- After selection, users can still use Delete and Backspace for editing
- …
=> BB-683: Cannot use HOME and END keyboard keys in text/select type/search fields

src/api/helpers/formatEntityData.ts, src/api/routes/edition.js, test/src/api/helpers.js, test/src/api/routes/test-edition.js
[BB-855](https://tickets.metabrainz.org/browse/BB-855) Add author and publisher information in edition API
Update the `/edition/{bbid}` endpoint to share the author and publisher information as well.
=> BB-855: Add author and publisher information in edition API
